<?php
$this->title = 'Xprice/consult';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/xprice/affiche_masque_commentaires.js');
$this->headScript()->appendFile('/js/controllers/xprice/afficher_masquer_validations.js');
?>
<div id="contenu" class="contenu">
    <h2>Consultation de l' offre</h2>
    <div id='workplace' class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table>
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->numwp; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo $this->dateplop; ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="information" class="workplace">
        <fieldset id="info_user" class="field_info">
            <legend>Informations Commercial</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_user['nom_user']; ?></td>
                </tr>
                <tr>
                    <td>Prénom:</td>
                    <td><?php echo $this->info_user['prenom_user']; ?></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><?php echo $this->info_user['email_user']; ?></td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td><?php echo $this->info_user['tel_user']; ?></td>
                </tr>
                <tr>
                    <td>Holon:</td>
                    <td><?php echo $this->holon; ?></td>
                </tr>
                <tr>
                    <td>User workplace:</td>
                    <td><?php echo $this->info_user['numwp_user']; ?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="info_client" class="field_info">
            <legend>Informations Client</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_client['nom_client']; ?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->info_client['numwp_client']; ?></td>
                </tr>
                <tr>
                    <td>Projet industrie:</td>
                    <td><?php echo $this->nom_industrie['nom_industry'] ?></td>
                </tr>
                <tr>
                    <td>Potentiel:</td>
                    <td><?php echo $this->info_client['potentiel']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="demandeArticle" class="workplace">
        <fieldset class="field" >
            <legend>Articles </legend>
            <table id="article" class="enum">
                <tr>
                    <th>code article</th>
                    <th>référence article</th>
                    <th>quantité</th>
                    <th>prix tarif</th>
                    <th>prix demandé</th>
                    <th>remise demandée</th>
                    <th>Prix accordés</th>
                    <th>Remises accordées</th>
                    <?php if($this->utilisateur =='5' or $this->utilisateur== '13'){ ?>
                    <th>Prix cif</th>
                    <th>Prix fob</th>
                    
                    <th>Marge</th><?php } else {}?>
                </tr>
                <?php foreach ($this->info_demande_article_xprice as $result) { ?>
                    <tr>
                        <td><?php echo $result['code_article']; ?></td>
                        <td><?php echo $result['reference_article']; ?></td>
                        <td><?php echo $result['quantite_demande_article']; ?></td>
                        <td><?php echo $result['prixwplace_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['prix_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['remise_demande_article'] . "%"; ?></td>
                        <?php if ( $result['prix_demande_article'] != $result['prix_accorde_demande_article']){ ?>
                        <td style="background-color: yellow;"><?php echo $result['prix_accorde_demande_article'] . "€"; ?></td>
                        <td style="background-color: yellow;"><?php echo $result['remise_accorde_demande_article'] . "%"; ?></td>
                        <?php }else{?>
                        <td><?php echo $result['prix_accorde_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['remise_accorde_demande_article'] . "%"; ?></td>
                        <?php }?>
                         <?php if($this->utilisateur =='5' or $this->utilisateur== '13'){ ?>
                        <td><?php echo $result['prix_cif_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['prix_fob_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['marge_demande_article'] . "%"; ?></td><?php } else {}?>
                    </tr>
                <?php } ?>
            </table>
             
        </fieldset>
    </div>
    <div id ='just_demande' class="workplace">
        <fieldset id = 'justif_user' class="field">
            <legend>Justificatif de la demande</legend>
           <table class="enum">
                <tr>
                    <th>Concurrent visé</th>
                    <th>Parts de marché smc</th>
                    <th>Minimum de commande</th>
                    <th>Démarche stratégique</th>
                </tr>
                <tr>
                    <td> <?php echo $this->info_demande_xprice['justificatif2_demande_xprice']; ?></td>
                    <td> <?php echo $this->info_demande_xprice['justificatif3_demande_xprice'] ?></td>
                    <td> <?php echo $this->info_demande_xprice['justificatif_demande_xprice'] ?></td>
                    <td> <?php if($this->info_demande_xprice['justificatif4_demande_xprice'] == 0) {echo 'concentration des efforts' ;} elseif($this->info_demande_xprice['justificatif4_demande_xprice'] == 1){ echo 'attaquer le faible';}elseif($this->info_demande_xprice['justificatif4_demande_xprice'] ==2 ){ echo 'globalisation';} ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id='commentaire' class="workplace">
        <button type="button" id="histButton" name="historique" value="historique" class="submit">Afficher les commentaires</button>
        <fieldset id='comm_user' class="field">
            <legend>Commentaires</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
    <div id="validation" class="workplace">
        <button class="submit" id="historiqueVal" name="historiqueVal" value="historiqueVal">Historique validation</button>
        <fieldset  id='valid_hist' class='field'>
            <legend>Validation</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['etat_validation']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
</div>

