<?php
$this->title = 'Xprice/list';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/xprice/affiche_masque_commentaires.js');
?>
<div id="contenu" class="contenu">
    <h2>Consultation de l' offre</h2>
    <div id='workplace' class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table>
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->numwp; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo $this->dateplop; ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="information" class="workplace">
        <fieldset id="info_user" class="field_info">
            <legend>Informations Commercial</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_user['nom_user']; ?></td>
                </tr>
                <tr>
                    <td>Prénom:</td>
                    <td><?php echo $this->info_user['prenom_user']; ?></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><?php echo $this->info_user['email_user']; ?></td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td><?php echo $this->info_user['tel_user']; ?></td>
                </tr>
                <tr>
                    <td>Holon:</td>
                    <td><?php echo $this->holon; ?></td>
                </tr>
                <tr>
                    <td>User workplace:</td>
                    <td><?php echo $this->info_user['numwp_user']; ?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="info_client" class="field_info">
            <legend>Informations Client</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_client['nom_client']; ?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->info_client['numwp_client']; ?></td>
                </tr>
                <tr>
                    <td>Projet industrie:</td>
                    <td><?php echo $this->nom_industrie['nom_industry'] ?></td>
                </tr>
                <tr>
                    <td>Potentiel:</td>
                    <td><?php echo $this->info_client['potentiel']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="demandeArticle" class="workplace">
        <fieldset class="field" >
            <legend>Articles </legend>
            <table id="article" class="enum">
                <tr>
                    <th>code article</th>
                    <th>référence article</th>
                    <th>quantité</th>
                    <th>prix workplace</th>
                    <th>prix demandé</th>
                    <th>remise demandée</th>
                </tr>
                <?php foreach ($this->info_demande_article_xprice as $result) { ?>
                    <tr>
                        <td><?php echo $result['code_article']; ?></td>
                        <td><?php echo $result['reference_article']; ?></td>
                        <td><?php echo $result['quantite_demande_article']; ?></td>
                        <td><?php echo $result['prixwplace_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['prix_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['remise_demande_article'] . "%"; ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
    <div id ='just_demande' class="workplace">
        <fieldset id = 'justif_user' class="field">
            <legend>Justificatif de la demande</legend>
            <span><?php echo $this->info_demande_xprice['justificatif_demande_xprice'] ?></span>
        </fieldset>
    </div>
    <div id='commentaire' class="workplace">
        <button type="button" id="histButton" name="historique" value="historique" class="submit">Afficher les commentaires</button>
        <fieldset id='comm_user' class="field">
            <legend>Commentaires</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
</div>

