 <?php
$this->title = 'Xprice/list';
$this->headTitle($this->title);
?>
 <h1>Consultation de l' offre</h1>
    <h3><?php echo $this->tracking_number; ?></h3>
        <div id="tableau">
            <table>
                <tr>
                    <th>tracking number</th>
                    <th>date de l'offre</th>
                    <th>client</th>
                    <th>montant de l'offre</th>
                    <th>détails</th>
                </tr>
                <tr>
                    <td><?php echo $this->tracking_number; ?></td>
                    <td><?php echo $this->date_offre; ?></td>
                    <td><?php echo $this->infos_client['nom_client']; ?></td>
                    <td><?php echo round($this->montant_total,2); ?></td>
                    <td><button id="bouton_objet" type="button" onclick="javascript:afficher('objet');">Détails</button></td>
                </tr>
            </table>
            <button type="button" name="historique" value="historique" class="submit"></button>
        </div>
               
    
