<?php
$this->title = 'Xprice/accueil';
$this->headTitle($this->title);

$this->headScript()->appendFile('/js/controllers/xprice/popup.js');
?>


<div class="contenu">
    <h2>Xprice</h2>
    <h3>Demande en ligne pour Prix Spéciaux</h3> 
    <table class="enum">
        <tr>
            <th>Tracking number</th>
            <th>Numéro Workplace</th>
            <th>Nom Client</th>
            <th>Date demande</th>
        </tr>
    <?php  foreach($this->recapitulatif as $k=>$result){
        ?><tr>
            <td><?php echo $result['num_workplace_demande_xprice']; ?></td>
            <td><?php echo $result['tracking_number_demande_xprice']; ?></td>
            <td><?php echo $result['nom_client']; ?></td>
             <td><?php echo $result['date_demande_xprice']; ?></td>
             <td></td>
             <td><button class="historique" id="historique-<?php echo $k; ?>">historique</button>
                 <div class='dialog' id="dialog-<?php echo $k; ?>">plop tagada</div>
             </td>
</tr>
   <?php }?>
    </table>
</div>