<?php
$this->title = 'Xprice/accueil';
$this->headTitle($this->title);
?>


<div class="contenu">
    <h2>Xprice</h3>
    <div>
        <table class="bouton">
            <tr>
                <td><button class="button"><a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'tracking'), null, true); ?>">Consulter une Xprice</a></button></td>
                <td><a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'numwp'), null, true); ?>"><button class="button">Créer une Xprice</button></a></td>
            </tr>
        </table>    
    </div>
</div>