<?php
$this->title = 'Xprice/accueil';
$this->headTitle($this->title);
?>


<div class="contenu">
    <h2>Xprice</h3>
    <button><a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'consult'), null, true); ?>">Consulter une Xprice</a></button>
    <button><a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'create'), null, true); ?>">Créer une Xprice</a></button>
</div>