 <?php
$this->title = 'Xprice/list';
$this->headTitle($this->title);
?>
 <h1>Consultation de l' offre</h1>
    <h3><?php echo $this->tracking_number; ?></h3>
        <div id="tableau">
            <table>
                <tr>
                    <th>tracking number</th>
                    <th>date de l'offre</th>
                    <th>client</th>
                    <th>montant de l'offre</th>
                    <th>détails</th>
                </tr>
                <tr>
                    <td><?php echo $this->tracking_number; ?></td>
                    <td><?php echo $this->date_demande_xprice; ?></td>
                    <td><?php echo $this->info_client['nom_client']; ?></td>
                    <td><?php $this->montant['total']; ?></td>
                    <td><button id="bouton_objet" type="button" onclick="javascript:afficher('objet');">Détail</button></td>
                </tr>
            </table>
            
        </div>
               
    
