<?php
$this->title = 'Xprice/fobfr';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/xprice/recalculeprix_marge.js');
$this->headScript()->appendFile('/js/controllers/xprice/afficher_masquer_validations.js');
?>
<div id="contenu" class="contenu">
    <h2> prix fob prix cif de l'offre n=°<?php echo $this->info_demande_xprice['tracking_number_demande_xprice'] ?></h2>
    <div id="workplace" class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table class="table_info">
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->numwp; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo str_replace("-", "/", $this->info_demande_xprice['date_demande_xprice']); ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div class="clear"></div>
    <div id="information" class="workplace">
        <fieldset id="info_user" class="field_info">
            <legend>Informations Commercial</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_user['nom_user']; ?></td>
                </tr>
                <tr>
                    <td>Prénom:</td>
                    <td><?php echo $this->info_user['prenom_user']; ?></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><?php echo $this->info_user['email_user']; ?></td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td><?php echo $this->info_user['tel_user']; ?></td>
                </tr>
                <tr>
                    <td>Holon:</td>
                    <td><?php echo $this->holon; ?></td>
                </tr>
                <tr>
                    <td>User workplace:</td>
                    <td><?php echo $this->info_user['numwp_user']; ?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="info_client" class="field_info">
            <legend>Informations Client</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_client['nom_client']; ?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->info_client['numwp_client']; ?></td>
                </tr>
                <tr>
                    <td>Projet industrie:</td>
                    <td><?php echo $this->nom_industrie['nom_industry']; ?></td>
                </tr>
                <tr>
                    <td>Potentiel:</td>
                    <td><?php echo $this->info_client['potentiel']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div class="clear"></div>
    <div id="commentaire" class="workplace">
        <fieldset class="field">
            <legend>Commentaires</legend>
            <table id="commentaires" class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
    <div class="clear"></div>
    <form method="post">
        <div id="demandeArticle" class="workplace">
            <fieldset class="field">
                <legend>Articles </legend>
                <table id="article" class="enum">
                    <tr>
                        <th>code article</th>
                        <th>référence article</th>
                        <th>quantité</th>
                        <th>prix tarif</th>
                        <th>prix demandé</th>
                        <th>remise demandée</th>
                        <th>prix fob</th>
                        <th>prix cif</th>
                        <th>Marge</th>
                    </tr>
                    <?php foreach ($this->info_demande_article_xprice as $k=>$result) { ?>
                        <tr>
                            <td><input readonly="readonly" value="<?php echo $result['code_article'] ?>"  name="<?php echo 'code_article[]'; ?>"></td>
                            <td style="width: 70px;"><?php echo $result['reference_article']; ?></td>
                            <td id="qt-<?php echo $k; ?>"><?php echo $result['quantite_demande_article']; ?></td>
                            <td id="pwp-<?php echo $k; ?>"><?php echo $result['prixwplace_demande_article']; ?></td>
                            <td id="pd-<?php echo $k; ?>"><?php echo $result['prix_demande_article']; ?></td>
                            <td><?php echo $result['remise_demande_article'] . "% "; ?></td>
                            <td><input id="prixfob" style="background-color: #74aaca;" type="text" name="prix_fob[]" value="<?php echo $result['prix_fob_demande_article']; ?>"></td>
                            <td><input class="prixcif" id="prixcif-<?php echo $k;?>" value="<?php echo $result['prix_cif_demande_article']; ?>" name="prix_cif[]" style="background-color: #74aaca;"></td>
                            <td><input class="margefob" id="margefob-<?php echo $k;?>" <?php $margefob=100*(1-($result['prix_cif_demande_article']/$result['prix_demande_article']));?> value="<?php  echo round($margefob,2)."%" ;?>" name="marge[]"></td>
                        </tr>
                    <?php } ?>
                        <tr>
                            <td colspan="6">total</td>
                            <input type ="hidden" class="cab" id="cab"
                               <?php $cab=0;foreach($this->info_demande_article_xprice as $result)
                                {$cab+=($result['quantite_demande_article']*$result['prixwplace_demande_article']);
                            
                            } ?>value="<?php echo $cab; ?>">
                            <input type="hidden" class="tpd" id="tpd" <?php  $tpd = 0; foreach($this->info_demande_article_xprice as $result){
                                $tpd+=($result['quantite_demande_article']*$result['prix_demande_article']);}?> value ="<?php echo $tpd ?>" >
                            
                            <td >
                                Cout FOB: <?php $Cfob=0; foreach($this->info_demande_article_xprice as $result){
                                    $Cfob+=($result['quantite_demande_article']*$result['prix_fob_demande_article']);
                                } echo $Cfob ."€"?>
                            </td>
                            <td>
                                Cout CIF: <input id="ccif"<?php $Ccif=0; foreach($this->info_demande_article_xprice as $result){
                                    $Ccif+=($result['quantite_demande_article']*$result['prix_cif_demande_article']);
                                }?> value="<?php echo $Ccif ."€"?>">
                            </td>
                            <td>marge moyenne <input id="mamofob" <?php $mamofob = 100*(1-($Ccif/$tpd))?> value ="<?php echo round($mamofob,2)."%";?>"></td>
                        </tr>
                </table>
                <input  type="hidden"  value="<?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?>" name="tracking_number">
                <input  type="hidden" value="<?php echo $this->date_validationfobfr; ?>">
            </fieldset>
        </div>
        <div class="clear"></div>
        <div id="comFob" class="workplace">
            <fieldset id="commFobs" class="field">
                <legend>Commentaire Fobfr</legend>
                <textarea name="commentaire_fobfr"></textarea>
            </fieldset>
        </div>
        <div class="clear"></div>
        <input id="ouiFob" class="submit" type="submit" value="valider prix fob">
    </form>
</div>
<div class="clear"></div>