<?php
$this->title = 'Xprice/recherche';
$this->headTitle($this->title);

$this->headScript()->appendFile('/js/controllers/xprice/popup.js');
?>
<div class="contenu">
    <h2>Xprice</h2>
    <h3>Résultats de la recherche</h3> 
    <table class="enum">
        <thead>
            <tr>
                <th>Commercial</th>
                <th>Numéro Workplace</th>
                <th>Tracking number</th>
                <th>Nom Client</th>
                <th>Date demande</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->listXprice as $result){?>
            <tr>
                <td><?php echo $result['nom_user'] ?></td>
                <td><?php echo $result['num_workplace_demande_xprice'] ?></td>
                <td><?php echo $result['tracking_number_demande_xprice'] ?></td>
                <td><?php echo $result['nom_client'] ?></td>
                <td><?php echo $result['date_demande_xprice']?></td>
                <td><a href="<?php echo $this->url(array("controller"=>"xprice","action"=>"consult","numwp"=>$result['num_workplace_demande_xprice']));?>" <button class="retour" id="historique-<?php echo $k; ?>">historique</button></a>
            </tr>
            <?php } ?>
        </tbody>
        
    </table>
</div>