<?php
$this->title = 'Xprice/recherche';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/multipleselect.js');
?>
<div class="contenu">
    <h2>Xprice</h2>
    <h3>Recherche Xprice par client </h3> 
    <form>
        <div class="workplace">
            <div id="widget1" class="ui-widget">
                <h4>recherche par client</h4>
                <select name="liste_client" id="combobox">
                    <option></option>
                    <?php foreach($this->result1 as $value1)
                    {?>
                    <option value="<?php echo $value1['id_client']; ?>"><?php echo $value1['nom_client']; ?></option>
                    <?php }?>
                </select>
            </div>
        </div>
        <div class="clear"></div>
    </form>
</div>
 <div class="clear"></div>