<?php
$this->title = 'Xprice/update';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/xprice/afficher_masquer_details.js');
?>
<div id="contenu" class="contenu">
    <h2>Mise à jour offre workplace </h2>
    <div id="info_demande" class="workplace">
        <table class="enum">
            <tr>
                <th>tracking_number</th>
                <th>date de l'offre</th>
                <th>client</th>
                <th>montant total de l'offre</th>
                <th>Détails</th>
            </tr>
            <tr>
                <td><?php echo $this->tracking_number; ?></td>
                <td><?php echo $this->date_offre; ?></td>
                <td><?php echo $this->infos_client['nom_client']; ?></td>
                <td><?php echo round($this->montant_total, 2) . "€"; ?></td>
                <td><button id="detailbutton" class="button" name="detailbutton" value="detailbutton" >Détails</button></td>
            </tr>
        </table>
    </div>
    <div id="details" class="contenu">
         <div id="demandeArticle" class="workplace">
        <fieldset class="field" >
            <legend>Articles </legend>
            <table id="article" class="enum">
                <tr>
                    <th>code article</th>
                    <th>référence article</th>
                    <th>quantité</th>
                    <th>prix workplace</th>
                    <th>prix demandé</th>
                    <th>remise demandée</th>
                </tr>
                <?php foreach ($this->info_demande_article_xprice as $result) { ?>
                    <tr>
                        <td><?php echo $result['code_article']; ?></td>
                        <td><?php echo $result['reference_article']; ?></td>
                        <td><?php echo $result['quantite_demande_article']; ?></td>
                        <td><?php echo $result['prixwplace_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['prix_demande_article'] . "€"; ?></td>
                        <td><?php echo $result['remise_demande_article'] . "%"; ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>   
    </div>
    <div id="comm_up" class="workplace">
        <form method="post">
            <fieldset class="field"><legend>Commentaires</legend>
                <?php
                /* aucun commentId n'existe dans le getrequest */
                if (!is_null($this->commentId)) {
                    ?>
                    <input type="hidden" name="reponse" value="<?php echo $this->commentId; ?>">
                    <?php
                }
                ?><table  class='enum'>
                <?php foreach (@$this->commentaire as $key => $value) { ?>
                        <tr><?php if ($value['etat_validation'] != "enAttente") { ?>
                                <td>Commentaire <?php echo strtolower($this->usersCommentaires[$key]['fonction']); ?></td>
                                <td><?php echo $value['date_validation']; ?></td>
                                <td><?php echo nl2br($value['commentaire']); ?></td>
                            </tr>
                        <?php
                        }
                    }
                    ?>
                </table>
            </fieldset >
            <fieldset class="field">
                <legend>Question</legend>
                <table  class='enum'>
                    <?php foreach (@$this->commentaire as $key => $value) { ?>
                    <tr>
                        <?php if ($value['etat_validation'] == "enAttente") { ?>
                        <td>Commentaire <?php echo strtolower($this->usersCommentaires[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                    <?php }}?>
                </table>
            </fieldset>
            <fieldset class="field">
                <legend>Réponse</legend>
                <textarea name="reponse_comm" cols="80" rows="10"></textarea>
            </fieldset>
            <input class="submit" type='submit' value="Envoyer la réponse">
        </form>
    </div>
</div>