<?php
$this->title = 'Xprice/update';
$this->headTitle($this->title);
?>
<h2>Mise à jour offre workplace </h2>
<div id="info_demande">
    <table class='article'>
        <tr>
            <th>tracking_number</th>
            <th>client</th>
            <th>date de l'offre</th>
            <th>montant total de l'offre</th>
            <th>Détails</th>
        </tr>
        <tr>
            <td>plop</td>
            <td>tagada</td>
            <td>tsouin</td>
            <td>truc</td>
            <td><input type="button" value='détails'></td>
        </tr>
    </table>
</div>
<div>
    <fieldset><legend>Commentaires</legend></fieldset>
    <form>
        <fieldset><legend>Question</legend></fieldset>
        <fieldset><legend>Réponse</legend></fieldset>
        <input class='plop' type='submit' value="Envoyer la réponse">
    </form>
</div>