<?php
$this->title = 'Xprice/update';
$this->headTitle($this->title);
?>
<h2>Mise à jour offre workplace </h2>
<div id="info_demande">
    <table class='article'>
        <tr>
            <th>tracking_number</th>
            <th>date de l'offre</th>
            <th>client</th>
            <th>montant total de l'offre</th>
            <th>Détails</th>
        </tr>
        <tr>
            <td><?php echo $this->tracking_number; ?></td>
            <td><?php echo $this->date_offre; ?></td>
            <td><?php echo $this->infos_client['nom_client']; ?></td>
            <td><?php echo round($this->montant_total, 2) . "€"; ?></td>
            <td><button id="bouton_objet" type="button" onclick="javascript:afficher('objet');">Détails</button></td>
        </tr>
    </table>
</div>
<div id="comm_up">
    <fieldset><legend>Commentaires</legend>
    <form>
        <?php /* aucun commentId n'existe dans le getrequest */
        if (!is_null($this->commentId)) {
            ?>
            <input type="hidden" name="reponse" value="<?php echo $this->commentId; ?>">
            <?php
        }
        ?><table  class='article'>
             <?php foreach (@$this->commentaire as $key => $value) { ?>
                <tr><?php if($value['etat_validation'] != "enAttente"){ ?>
                    <td>Commentaire <?php echo strtolower($this->usersCommentaires[$key]['fonction']); ?></td>
                    <td><?php echo $value['date_validation']; ?></td>
                    <td><?php echo nl2br($value['commentaire']); ?></td>
                </tr>
                <?php } } ?>
</table>
    </fieldset>
        <fieldset>
            <legend>Question</legend>
            <table  class='article'>
                 <?php foreach (@$this->commentaire as $key => $value) { ?>
                <tr><?php if($value['etat_validation'] == "enAttente"){ ?>
                    <td>Commentaire <?php echo strtolower($this->usersCommentaires[$key]['fonction']); ?></td>
                    <td><?php echo $value['date_validation'];?></td>
                     <td><?php echo nl2br($value['commentaire']); ?></td>
                </tr>
                <?php } } ?>
            </table>
        </fieldset>
        <fieldset>
            <legend>Réponse</legend>
            <textarea name="reponse_comm" cols="80" rows="10">
                
            </textarea>
            
        </fieldset>
        <div id="plop">
            <input class="plop" type='submit' value="Envoyer la réponse">
        </div>
    </form>
</div>