<?php
$this->title = 'Xprice/supplyChain';
$this->headTitle($this->title);
?>
<div id="contenu" class="contenu">
    <h2>Validation des prix fob/cif <br>offre n=°<?php echo $this->info_demande_xprice['tracking_number_demande_xprice'] ?> par le supply chain manager</h2>
    <div id='workplace' class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table>
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->numwp; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo str_replace("-", "/", $this->info_demande_xprice['date_demande_xprice']); ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="information" class="workplace">
        <fieldset id="info_user" class="field_info">
            <legend>Informations Commercial</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_user['nom_user']; ?></td>
                </tr>
                <tr>
                    <td>Prénom:</td>
                    <td><?php echo $this->info_user['prenom_user']; ?></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><?php echo $this->info_user['email_user']; ?></td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td><?php echo $this->info_user['tel_user']; ?></td>
                </tr>
                <tr>
                    <td>Holon:</td>
                    <td><?php echo $this->holon; ?></td>
                </tr>
                <tr>
                    <td>User workplace:</td>
                    <td><?php echo $this->info_user['numwp_user']; ?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="info_client" class="field_info">
            <legend>Informations Client</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_client['nom_client']; ?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->info_client['numwp_client']; ?></td>
                </tr>
                <tr>
                    <td>Projet industrie:</td>
                    <td><?php echo $this->nom_industrie['nom_industry']; ?></td>
                </tr>
                <tr>
                    <td>Potentiel:</td>
                    <td><?php echo $this->info_client['potentiel']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="commentaire" class="workplace">
        <fieldset class="field">
            <legend>Commentaires</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
    <form action="" method="post">
        <div id="demandeArticle" class="workplace">
            <fieldset class="field">
                <legend>Articles </legend>
                <table id="article" class="enum">
                    <tr>
                        <th>code article</th>
                        <th>référence article</th>
                        <th>quantité</th>
                        <th>prix tarif</th>
                        <th>prix demandé</th>
                        <th>remise demandée</th>
                        <th>prix fob</th>
                        <th>prix cif</th>
                        <th>Marge</th>
                    </tr>
                    <?php foreach ($this->info_demande_article_xprice as $result) { ?>
                        <tr>
                            <td><input readonly="readonly" value="<?php echo $result['code_article'] ?>"  name="<?php echo 'code_article[]'; ?>"></td>
                            <td><?php echo $result['reference_article']; ?></td>
                            <td id="qt-<?php echo $k; ?>"><?php echo $result['quantite_demande_article']; ?></td>
                            <td id="pwp-<?php echo $k; ?>"><?php echo $result['prixwplace_demande_article']; ?></td>
                            <td><?php echo $result['prix_demande_article']; ?></td>
                            <td><?php echo $result['remise_demande_article'] . "% "; ?></td>
                            <td><input id="prixfob" style="background-color: #74aaca;" type="text" name="prix_fob[]" value="<?php echo $result['prix_fob_demande_article']; ?>"></td>
                            <td><input id="prixcif" style="background-color: #74aaca;" type="text" name="prix_cif[]" value="<?php echo $result['prix_cif_demande_article']; ?>"></td>
                            <td><input  value="<?php $marge=100*(1-($result['prix_cif_demande_article']/$result['prix_demande_article'])); echo round($marge,2)."%" ;?>" name="marge[]"</td>
                        </tr>
                    <?php } ?>
                        <tr>
                            <td colspan ="8">
                                
                            </td>
                        </tr>
                </table>
                <input type="text" hidden="hidden" value="<?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?>" name="tracking_number">
                <input type="text" hidden="hidden" value="<?php echo $this->date_validation_supply; ?>" name="date_validation_supply">
            </fieldset>
        </div>
        <div id='formprixfob' class="workplace">
            <fieldset id='form_prixfob' class="field">
                <legend>Commentaire Supply chain Manager</legend>
                <textarea name="commentaire_supply" cols="50" rows="20"></textarea>
                <?php
                if (!is_null($this->commentId)) {
                    ?>
                    <input type="hidden" name="reponse" value="<?php echo $this->commentId; ?>"> <?php }?>
            </fieldset>
        </div>
        <input class="submit" type="submit" value="validation prix fob">    
    </form>
</div>