<?php
$this->title = 'Xprice/validateChefregion';
$this->headTitle($this->title);
?>
<div id='workplace'>
    <fieldset id="wp">
        <legend>Informations offre</legend>
        <table>
            <tr>
                <td>Numéro workplace de l'offre :</td>
                <td><?php echo $this->numwp; ?></td>
            </tr>
            <tr>
                <td>Date de l'offre workplace :</td>
                <td><?php echo  $this->dateplop; ?></td>
            </tr>
            <tr>
                <td>Tracking number :</td>
                <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
            </tr>
        </table>
    </fieldset>
</div>
<div id="information">
    <fieldset id="info_user">
        <legend>Informations Commercial</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><?php echo $this->info_user['nom_user'];?></td>
            </tr>
            <tr>
                <td>Prénom:</td>
                <td><?php echo $this->info_user['prenom_user'];?></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><?php echo $this->info_user['email_user'];?></td>
            </tr>
            <tr>
                <td>Téléphone:</td>
                <td><?php echo $this->info_user['tel_user'];?></td>
            </tr>
            <tr>
                <td>Holon:</td>
                <td><?php echo $this->holon; ?></td>
            </tr>
            <tr>
                <td>User workplace:</td>
                <td><?php echo $this->info_user['numwp_user'];?></td>
            </tr>
        </table>
    </fieldset>
    <fieldset id="info_client">
    <legend>Informations Client</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><?php echo $this->info_client['nom_client'];?></td>
            </tr>
            <tr>
                <td>User Workplace:</td>
                <td><?php echo $this->info_client['numwp_client'];?></td>
            </tr>
            <tr>
                <td>Projet industrie:</td>
                <td><?php  echo $this->nom_industrie['nom_industry']?></td>
            </tr>
            <tr>
                <td>Potentiel:</td>
                <td><?php echo $this->info_client['potentiel']; ?></td>
            </tr>
        </table>
    </fieldset>
</div>
<div id="demandeArticle">
    <fieldset ><legend>Articles </legend>
        <table id="article">
            <tr>
                <th>code article</th>
                <th>référence article</th>
                <th>quantité</th>
                <th>prix workplace</th>
                <th>prix demandé</th>
                <th>remise demandée</th>
            </tr>
            <?php foreach ($this->info_demande_article_xprice as $result) { ?>
                <tr>
                    <td><?php echo $result['code_article'];?></td>
                    <td><?php echo $result['reference_article'];?></td>
                    <td><?php echo $result['quantite_demande_article'];?></td>
                    <td><?php echo $result['prixwplace_demande_article'];?></td>
                    <td><?php echo $result['prix_demande_article'];?></td>
                    <td><?php echo $result['remise_demande_article']; ?></td>
                </tr>
            <?php } ?>
        </table>
    </fieldset>
</div>
<div id ='just_demande'>
    <fieldset id = 'justif_user'><legend>Justificatif de la demande</legend>
        <span><?php echo $this->info_demande_xprice['justificatif_demande_xprice'] ?></span>
    </fieldset>
</div>
<div id='comm_demande'>
    <fieldset id='comm_user'><legend>Commentaire commercial</legend>
        <span><?php echo $this->info_demande_xprice['commentaire_demande_xprice'] ?></span>
    </fieldset>
</div>
<form method="post">
    <div id='cdr'>
        <fieldset>
            <legend>Commentaire chef de région</legend>
            <textarea name="commentaire_chefregion" cols="75" rows="10"></textarea>
        </fieldset>
    </div>
    <div id="valid_cdr">
        <input type="radio" name="validation" value="nonValide"> La demande n'est pas validée <br>
        <input type="radio" name="validation" value="validee"> La demande est validée <br>
        <input type="radio" name="validation" value="enAttente">  en attente de réponse  <br> 
        <input hidden="hidden" name="nom_validation" value="validation_cdr">
        <input hidden="hidden" name="date_validation" value="<?php echo date("Y-m-d H:i:s")?>">
        <input hidden="hidden" name="cdr" value="<?php echo $this->cdr;?>">
        <input hidden="hidden" name="tracking" value="<?php echo $this->info_demande_xprice['tracking_number_demande_xprice'] ;?>"> 
   </div>
        
    <input type="submit" value="enregistrer">
        
</form>