<?php
$this->title = 'Xprice/validatedbd';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/xprice/recalculeprix_marge.js');
$this->headScript()->appendFile('/js/controllers/xprice/afficher_masquer_validations.js');
?>
<div id="contenu" class="contenu">
    <h2>Validation de l'offre<br><?php echo $this->info_demande_xprice['tracking_number_demande_xprice'] ?> par le DBD</h2>
    <div id='workplace' class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table>
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->numwp; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo $this->dateplop; ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="information" class="workplace">
        <fieldset id="info_user" class="field_info">
            <legend>Informations Commercial</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_user['nom_user']; ?></td>
                </tr>
                <tr>
                    <td>Prénom:</td>
                    <td><?php echo $this->info_user['prenom_user']; ?></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><?php echo $this->info_user['email_user']; ?></td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td><?php echo $this->info_user['tel_user']; ?></td>
                </tr>
                <tr>
                    <td>Holon:</td>
                    <td><?php echo $this->holon; ?></td>
                </tr>
                <tr>
                    <td>User workplace:</td>
                    <td><?php echo $this->info_user['numwp_user']; ?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="info_client" class="field_info">
            <legend>Informations Client</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->info_client['nom_client']; ?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->info_client['numwp_client']; ?></td>
                </tr>
                <tr>
                    <td>Projet industrie:</td>
                    <td><?php echo $this->nom_industrie['nom_industry']; ?></td>
                </tr>
                <tr>
                    <td>Potentiel:</td>
                    <td><?php echo $this->info_client['potentiel']; ?></td>
                </tr>
                <tr>
                    <td>CA total N-1 réalisé par le client:</td>
                    <td></td>
                </tr>
                <tr>
                    <td>CA cumulé à date sur l'année en cours :</td>
                    <td></td>
                </tr>
                <tr>
                    <td>% progression à date année en cours VS année N-1 :</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Marge totale du client année N-1 et pour l'année en cours :</td>
                    <td></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="commentaire" class="workplace">
        <fieldset class="field">
            <legend>Commentaires</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
    <form action="" method="post">
        <div id="demandeArticle" class="workplace">
            <fieldset class="field">
                <legend>Articles </legend>
                <table id="article" class="enum">
                    <tr>
                        <th>code article</th>
                        <th>référence article</th>
                        <th>quantité</th>
                        <th>prix workplace</th>
                        <th>prix demandé</th>
                        <th>remise demandée</th>
                        <th>prix fob</th>
                        <th>prix cif</th>
                        <th>prix accordé</th>
                        <th>remise accordée</th>
                        <th>marge</th>
                    </tr>
                    <?php foreach ($this->info_demande_article_xprice as $k => $result) { ?>
                        <tr>
                            <td><input readonly="readonly" value="<?php echo $result['code_article']; ?>"  name="<?php echo 'code_article[]'; ?>"></td>
                            <td><?php echo $result['reference_article']; ?></td>
                            <td><?php echo $result['quantite_demande_article']; ?></td>
                            <td id="pwp-<?php echo $k; ?>"><?php echo $result['prixwplace_demande_article']; ?></td>
                            <td><?php echo $result['prix_demande_article']; ?></td>
                            <td><?php echo $result['remise_demande_article'] . "% "; ?></td>
                            <td><?php echo $result['prix_fob_demande_article']; ?></td>
                            <td id="cif-<?php echo $k; ?>"><?php echo $result['prix_cif_demande_article']; ?></td>
                            <td><input class="pda" id="pda-<?php echo $k; ?>" value="<?php echo $result['prix_demande_article']; ?>" name="<?php echo 'prix_accorde_article[]' ?>" style="background-color: #74aaca;"></td>
                            <td><input class="ra" id="ra-<?php echo $k; ?>" value="<?php echo $result['remise_demande_article'] . "%"; ?>" name="<?php echo 'remise_accorde_article[]' ?>" style="background-color: #74aaca;"></td>
                            <td><input  class="ma" id="ma-<?php echo $k;?>"  value="<?php echo round( $result['marge_demande_article'],2); ?>" name="<?php echo 'marge_demande_article[]';?>" style="background-color: #74aaca;"></td>
                        </tr>
                    <?php } ?>
                </table>
            </fieldset>
        </div>
        <div id="validation" class="workplace">
        <button class="submit" id="historiqueVal" name="historiqueVal" value="historiqueVal">Historique validation</button>
        <fieldset  id='valid_hist' class='field'>
            <legend>Validation</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['etat_validation']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
        <div id='commentaire_dirco' class="workplace">
            <fieldset class="field">
                <legend>Commentaire DBD</legend>
                <textarea name="commentaire_dbd" cols="80" rows="10"></textarea>
                <?php
                if (!is_null($this->commentId)) {
                    ?>
                    <input type="hidden" name="reponse" value="<?php echo $this->commentId; ?>">
                    <?php
                }
                ?>
            </fieldset>
        </div>
        <div id="valid_dirco" class="workplace">
            <input type="radio" name="validation" value="nonValide"> La demande n'est pas validée <br>
            <input type="radio" name="validation" value="validee"> La demande est validée <br>
            <input type="radio" name="validation" checked="checked" value="enAttente">  en attente de réponse  <br>
            <input hidden="hidden" name="nom_validation" value="validation_dbd">
            <input hidden="hidden" name="date_validation" value="<?php echo date("Y-m-d H:i:s") ?>">
            <input hidden="hidden" name="dbd" value="<?php echo $this->dbd; ?>">
            <input hidden="hidden" name="tracking" value="<?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?>">
        </div>
            <input class="submit" type="submit" value="enregistrer statut offre">
    </form>
</div>