<?php
$this->title = 'Xprice/validatedirco';
$this->headTitle($this->title);
?>
<h2>Validation de l'offre<br><?php echo $this->info_demande_xprice['tracking_number_demande_xprice'] ?> par le Directeur commercial</h2>
    <div id='workplace'>
    <fieldset id="wp">
        <legend>Informations offre</legend>
        <table>
            <tr>
                <td>Numéro workplace de l'offre :</td>
                <td><?php echo $this->numwp; ?></td>
            </tr>
            <tr>
                <td>Date de l'offre workplace :</td>
                <td><?php echo $this->dateplop; ?></td>
            </tr>
            <tr>
                <td>Tracking number :</td>
                <td><?php echo $this->info_demande_xprice['tracking_number_demande_xprice']; ?></td>
            </tr>
        </table>
    </fieldset>
</div>
<div id="information">
        <fieldset id="info_user">
        <legend>Informations Commercial</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><?php echo $this->info_user['nom_user'];?></td>
            </tr>
            <tr>
                <td>Prénom:</td>
                <td><?php echo $this->info_user['prenom_user'];?></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><?php echo $this->info_user['email_user'];?></td>
            </tr>
            <tr>
                <td>Téléphone:</td>
                <td><?php echo $this->info_user['tel_user'];?></td>
            </tr>
            <tr>
                <td>Holon:</td>
                <td><?php echo $this->holon; ?></td>
            </tr>
            <tr>
                <td>User workplace:</td>
                <td><?php echo $this->info_user['numwp_user'];?></td>
            </tr>
        </table>
    </fieldset>
    <fieldset id="info_client">
        <legend>Informations Client</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><?php echo $this->info_client['nom_client'];?></td>
            </tr>
            <tr>
                <td>User Workplace:</td>
                <td><?php echo $this->info_client['numwp_client'];?></td>
            </tr>
            <tr>
                <td>Projet industrie:</td>
                <td><?php echo $this->nom_industrie['nom_industry'];?></td>
            </tr>
            <tr>
                <td>Potentiel:</td>
                <td><?php echo $this->info_client['potentiel'];?></td>
            </tr>
        </table>
    </fieldset>
</div>
    <div id="commentaire"> 
        <fieldset><legend>Commentaires</legend>
        <table>
            <tr>
                <td>Commmentaire Commercial</td>
                <td></td>
            </tr>
            <?php foreach ($this->info_validation as $value) {?>
            <tr>
                <td>Commentaire <?php if($value['nom_validation'] =="validation_cdr"){echo "chef de région";} elseif ($value['nom_validation'] =="fobfr"){echo "fobfr";}elseif($value['nom_validation'] =="supply"){echo "supply chain manager";}
                
              ?></td>
                <td><?php if($value['nom_validation'] =="validation_cdr"){echo $value['commentaire_validation'];}elseif ($value['nom_validation'] =="fobfr"){echo $value['commentaire_validation'];}elseif($value['nom_validation'] =="supply"){echo $value['commentaire_validation'];}?></td>
            </tr>
                
                
          <?php  } ?>
        </table>
        </fieldset>
    </div>
<div id="formulairedirco">
    <form action="" method="post">
<div id="demandeArticle">
    <fieldset ><legend>Articles </legend>
        <table id="article">
            <tr>
                <th>code article</th>
                <th>référence article</th>
                <th>quantité</th>
                <th>prix workplace</th>
                <th>prix demandé</th>
                <th>remise demandée</th>
                <th>prix fob</th>
                <th>prix cif</th>
                <th>prix accordé</th>
                <th>remise accordée</th>
            </tr>
            <?php foreach ($this->info_demande_article_xprice as $result) { ?>
                <tr>
                    <td><?php echo $result['code_article']; ?></td>
                    <td><?php echo $result['reference_article'];?></td>
                    <td><?php echo $result['quantite_demande_article'];?></td>
                    <td><?php echo $result['prixwplace_demande_article'];?></td>
                    <td><?php echo $result['prix_demande_article']; ?></td>
                    <td><?php echo $result['remise_demande_article'] ."% ";?></td>
                    <td><?php echo $result['prix_fob_demande_article']; ?></td>
                    <td><?php echo $result['prix_cif_demande_article']; ?></td>
                    <td><input value="" name="" style="background-color: #74aaca;"></td>
                    <td><input value="" name="" style="background-color: #74aaca;"></td>
                </tr>
            <?php } ?>
        </table>
        <input type="text" hidden="hidden" value="<?php echo  $this->info_demande_xprice['tracking_number_demande_xprice']; ?>" name="tracking_number">
        <input type="text" hidden="hidden" value="<?php echo  $this->date_validation_supply; ?>" name="date_validation_supply">
    </fieldset>  
</div>
<div id='commentaire_dirco'>
    <fieldset><legend>Commentaire Directeur Commercial</legend>
        <textarea name="commentaire_dirco" cols="50" rows="20"></textarea>
    </fieldset>
</div>
<div>
    <input type="submit" value="enregistrer">
</div>
</form>
</div>