<div class="contenu">
    <h2>Xprev</h2>
    <h3>traitement de la prévision: <?php echo $this->infoPrev['tracking'] ;?>  traitée</h3>
    <fieldset class="field">
        <legend>Informations générales</legend>
        <table id="information3">
            <tr> 
                <td>date de création</td>
                <td><?php echo $this->infoPrev['date_create'] ;?></td>
                <td>niveau de risque</td>
                <td><?php echo $this->infoPrev['nom_risque_xprev'] ;?></td>
                <td>code client</td>
                <td><?php echo $this->infoPrev['code_user_client_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>statut</td>
                <td><?php echo $this->infoPrev['nom_validation_xprev'] ;?></td>
                <td>type de demande</td>
                <td><?php echo $this->infoPrev['nom_type_demande_xprev'] ;?></td>
                <td>nom client</td>
                <td><?php echo $this->infoPrev['nom_client_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>émetteur prévision</td>
                <td><?php echo $this->infoPrev['nom_user'] ;?></td>
                <td>date de début de prévision</td>
                <td><?php echo $this->infoPrev['date_debut'] ;?></td>
                <td>code user</td>
                <td><?php echo $this->infoPrev['code_client_users_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>commercial</td>
                <td><?php echo $this->infoPrev['nom_commercial'] ;?></td>
                <td></td>
                <td></td>
                <td>nom user</td>
                <td><?php echo $this->infoPrev['nom_client_user_xprev'] ;?></td>
            </tr>
        </table>
        
        <p>motif  de la demande :<?php echo $this->infoPrev['justification'] ;?></p>
        <?php if( $this->infoPrev['justification_n1']!= null) { ?>
        <p>validation n+1 :<?php echo $this->infoPrev['justification_n1'] ;?></p>
        <?php } ;?>
        <?php if( $this->infoPrev['justification_log']!= null) { ?>
        <p>validation n+1 :<?php echo $this->infoPrev['justification_log'] ;?></p>
        <?php } ;?>
        
        <p class="decale">fichier joint :<?php foreach ($this->infoFichier as $fichier){ ?> <a class="fichier_joint" href=" <?php echo $fichier['chemin_fichier_xprev']; ?>" target="_blank"><?php echo $fichier['nom_fichier_xprev']; ?></a><br><?php  }?></p>
    </fieldset>
    <fieldset class="field">
        <legend>Informations article</legend>
        <table class="enum">
            <thead>
                <tr>
                    <th>référence</th>
                    <th>code article</th>
                     <?php if($this->infoUser['niveau']=='niveau4'){ ;?>
                    <th>prix de revient</th>
                    <th>shikomi</th>
                    <?php }?>
                    <?php foreach ($this->infoMois as $mois){ ?>
                    <th><?php echo $mois['month'] ."/".$mois['year']?></th><?php }?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->infoArticle as $article){ ?>
                <tr>
                    <td><?php echo $article['reference_article'] ;?></td>
                    <td><?php echo $article['code_article'] ;?></td>
                    <?php if($this->infoUser['niveau']=='niveau4'){ ;?>
                    <td><?php echo $article['prix_revient'] ;?></td>
                    <td><?php if($article['shikomi']==1){?><input type="checkbox" checked="checked"><?php }else { ?><input type="checkbox" readonly disabled></td>
                    <?php } }?>
                    <td><?php echo $article['m1'] ;?></td>
                    <td><?php echo $article['m2'] ;?></td>
                    <td><?php echo $article['m3'] ;?></td>
                    <td><?php echo $article['m4'] ;?></td>
                    <td><?php echo $article['m5'] ;?></td>
                    <td><?php echo $article['m6'] ;?></td>
                    <td><?php echo $article['m7'] ;?></td>
                    <td><?php echo $article['m8'] ;?></td>
                    <td><?php echo $article['m9'] ;?></td>
                    <td><?php echo $article['m10'] ;?></td>
                    <td><?php echo $article['m11'] ;?></td>
                    <td><?php echo $article['m12'] ;?></td>
                    <?php if($this->infoUser['niveau']=='niveau4'){ ;?>
                    <?php $total[].=+ $article['valeur_totale']; ?>
                    <?php }?>
                </tr>
               
                <?php  }?><tr>
                    <td colspan="13"></td>
                    <td colspan="3"><?php echo "valeur totale=" . array_sum($total) ; ?></td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <form action="#" method="post" enctype="multipart/form-data">
        
        <fieldset class="field">
            <legend>Informations supplémentaires </legend>
            
            <p class="obligatoire">commentaire :</p>
            <textarea required name="motif_validation" cols="120" rows="7" value=""></textarea>
            <p>Ajout de document : <input type="file" value="" name="fichierClotureXprev"></p>
            <div class="soumission">
                <input class="submit2" type="submit" value="envoyer">
            </div>
        </fieldset>
    </form>
</div>