<div class="contenu">
    <h2>Xprev</h2>
    <h3>Consultation de la demande de prev: <?php echo $this->infoPrev['tracking'] ;?> </h3>
    <table>
        <tr> 
            <td>date de création</td>
            <td></td>
            <td>niveau de risque</td>
            <td></td>
            <td>code client</td>
            <td></td>
        </tr>
        <tr> 
            <td>statut</td>
            <td></td>
            <td>type de demande</td>
            <td></td>
            <td>nom client</td>
            <td></td>
        </tr>
        <tr> 
            <td>émetteur prévision</td>
            <td></td>
            <td>date de début de prévision</td>
            <td></td>
            <td>code user</td>
            <td></td>
        </tr>
        <tr> 
            <td>commercial</td>
            <td></td>
            <td>ajout de document</td>
            <td></td>
            <td>nom user</td>
            <td></td>
        </tr></table>
    <p class="obligatoire">motif  de la demande :</p>
    <table>
        <thead>
        </thead>
        <tbody></tbody>
    </table>
</div>