<div class="contenu">
    <h2>Xprev</h2>
    <h3>Consultation de la demande de prev: <?php echo $this->infoPrev['tracking'] ;?> </h3>
    <fieldset class="field">
        <legend>Informations générales</legend>
        <table id="information3">
            <tr> 
                <td>date de création</td>
                <td><?php echo $this->infoPrev['date_create'] ;?></td>
                <td>niveau de risque</td>
                <td><?php echo $this->infoPrev['nom_risque_xprev'] ;?></td>
                <td>code client</td>
                <td><?php echo $this->infoPrev['code_user_client_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>statut</td>
                <td><?php echo $this->infoPrev['nom_validation_xprev'] ;?></td>
                <td>type de demande</td>
                <td><?php echo $this->infoPrev['nom_type_demande_xprev'] ;?></td>
                <td>nom client</td>
                <td><?php echo $this->infoPrev['nom_client_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>émetteur prévision</td>
                <td><?php echo $this->infoPrev['nom_user'] ;?></td>
                <td>date de début de prévision</td>
                <td><?php echo $this->infoPrev['date_debut'] ;?></td>
                <td>code user</td>
                <td><?php echo $this->infoPrev['code_client_users_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>commercial</td>
                <td><?php echo $this->infoPrev['nom_commercial'] ;?></td>
                <td></td>
                <td></td>
                <td>nom user</td>
                <td><?php echo $this->infoPrev['nom_client_user_xprev'] ;?></td>
            </tr>
        </table>
        
        <p>motif  de la demande :<?php echo $this->infoPrev['justification'] ;?></p>
        <?php if( $this->infoPrev['justification_n1']!= null) { ?>
        <p>commentaire n+1 :<?php echo $this->infoPrev['justification_n1'] ;?></p>
        <?php } ?>
        
        <?php if( $this->infoPrev['justification_log']!= null) { ?>
        <p>commentaire logistique :<?php echo $this->infoPrev['justification_log'] ;?></p>
        <?php } ?>
        <?php if( $this->infoPrev['justification_dop']!= null) { ?>
        <p>commentaire directeur des opérations :<?php echo $this->infoPrev['justification_dop'] ;?></p>
        <?php } ?>
        <?php if( $this->infoPrev['justification_traitement']!= null) { ?>
        <p>commentaire traitement :<?php echo $this->infoPrev['justification_traitement'] ;?></p>
        <?php } ?>
        <?php if( $this->infoPrev['justification_cloture']!= null) { ?>
        <p>commentaire:<?php echo $this->infoPrev['justification_cloture'] ;?></p>
        <?php } ?>
        
         <?php if( !empty($this->infoFichier)) { ?>
        <p class="decale">fichier joint creation:<?php foreach ($this->infoFichier as $fichier){ ?> <a href=" <?php echo $fichier['chemin_fichier_xprev']; ?>" target="_blank"><?php echo $fichier['nom_fichier_xprev']; ?></a><br><?php  }?></p>
         <?php } ?>
        <?php if(!empty($this->infodemandeinfolog)){ ?>
    <fieldset class="field">
        <legend>demande d'information logistique</legend>
         <?php foreach ($this->infodemandeinfolog as $demandeinfolog){ ?>
             <p>demande :<?php echo $demandeinfolog['demande_infolog'] ;?></p>
             <p>réponse:<?php echo $demandeinfolog['reponse_infolog'] ;?></p>
         <?php }?>
    </fieldset>
        <?php } ?>
        <?php if(!empty($this->infodemandeinfodop)){ ?>
    <fieldset class="field">
        <legend>demande d'information</legend>
         <?php foreach ($this->infodemandeinfodop as $demandeinfodop){ ?>
             <p>demande :<?php echo $demandeinfodop['demande_infodop'] ;?></p>
             <p>réponse:<?php echo $demandeinfodop['reponse_infodop'] ;?></p>
         <?php }?>
    </fieldset>
         <?php }?>
        <?php if(!empty($this->infocloture)){ ?>
    <fieldset class="field">
        <legend>complément d'information</legend>
         <?php foreach ($this->infocloture as $infocloturesupp){ ?>
             <p><?php echo $infocloturesupp['infoclot'] ;?></p>
         <?php }?>
    </fieldset>
         <?php }?>
    </fieldset>
    <fieldset class="field">
        <legend>Informations article</legend>
        <table class="enum">
            <thead>
                <tr>
                     <?php if($this->infoUser['niveau']=='niveau4' && $this->infoUser['fonction'] != 50){ ;?>
                    <th>référence</th>
                    <th>code article</th>
                     <?php }else { ?><th colspan="3">référence</th> <?php }?>
                     <?php if($this->infoUser['niveau']=='niveau4'){ ?>
                    <th>CU</th>
                    <th>shikomi</th>
                    <?php }?>
                    <?php foreach ($this->infoMois as $mois){ ?>
                    <th><?php echo $mois['month'] ."/".$mois['year']?></th><?php }?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->infoArticle as $article){ ?>
                <tr>
                     <?php if($this->infoUser['niveau']=='niveau4' && $this->infoUser['fonction'] != 50){ ;?>
                    <td><?php echo $article['reference_article'] ;?></td>
                    <td><?php echo $article['code_article'] ;?></td>
                     <?php }else { ?><td colspan="3" ><?php echo $article['reference_article'] ;?></td> <?php }?>
                    <?php if($this->infoUser['niveau']=='niveau4'){ ?>
                    <td><?php echo $article['prix_revient']; ?></td>
                    <td><?php if($article['shikomi']==1){?><input type="checkbox" checked="checked" readonly disabled><?php }else { ?><input type="checkbox" readonly disabled></td>
                    <?php }}?>
                    <td><?php echo $article['m1'] ;?></td>
                    <td><?php echo $article['m2'] ;?></td>
                    <td><?php echo $article['m3'] ;?></td>
                    <td><?php echo $article['m4'] ;?></td>
                    <td><?php echo $article['m5'] ;?></td>
                    <td><?php echo $article['m6'] ;?></td>
                    <td><?php echo $article['m7'] ;?></td>
                    <td><?php echo $article['m8'] ;?></td>
                    <td><?php echo $article['m9'] ;?></td>
                    <td><?php echo $article['m10'] ;?></td>
                    <td><?php echo $article['m11'] ;?></td>
                    <td><?php echo $article['m12'] ;?></td>
                    
                <?php  echo $total[].=+ $article['valeur_totale'];} ?>
                    <?php if($this->infoUser['niveau']=='niveau4'){ ?>
                </tr>
                <tr>
                    <td colspan="13"></td>
                    <td colspan="3"><?php echo "valeur totale=" . array_sum($total) ; ?></td>
                </tr>
                    <?php }?>
            </tbody>
        </table>
        <p></p>
    </fieldset>
</div>