<?php
$this->title = 'Xprev/creation';
$this->headTitle($this->title);
$this->headLink()->appendStylesheet('/css/jquery-ui.css');
$this->headScript()->appendFile('/js/controllers/xprev/codeclient.js');
$this->headScript()->appendFile('/js/controllers/xprev/datepicker.js');
$this->headScript()->appendFile('/js/controllers/xprev/MonthPicker.js');
//$this->headScript()->appendFile('/js/controllers/xprev/ajoutarticle.js');
$this->headScript()->appendFile('/js/controllers/xprev/verifReference.js');
$this->headLink()->appendStylesheet('/css/MonthPicker.css');

//<table style="display: none;" >
//    <tbody>
?>
<script type="text/html" id="addRefTPL">
        <tr>
            <td><button class="resetbuton" data-id="__id__" name="boutonreset[_id_]">reset</button></td>
            <td><input class="refartReference" data-id="__id__" type="text" name="refart[__id__][reference]" value="" /></td>
            <td><input type="text" name="refart[__id__][code_article]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m1]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m2]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m3]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m4]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m5]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m6]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m7]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m8]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m9]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m10]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m11]" value="" /></td>
            <td><input class="petit_input" type="text" name="refart[__id__][m12]" value="" /></td>
        </tr>
</script>
<div class="contenu">
    <h2>Xprev</h2>
    <h3> création de Demande de prévision en ligne </h3>
    <form method="post" enctype="multipart/form-data" action="#" >
        <table>
            <tr> 
                <td>date de création</td>
                <td><input  type="text" name="date_create" value="<?php echo $this->datecreate ;?>"></td>
                <td>niveau de risque</td>
                <td>
                    <select required>
                        <option>choisissez un niveau de risque</option>
                    <?php foreach($this->listeniveaurisque as $listeniveau ){?>
                        <option><?php echo $listeniveau['nom_risque_xprev']?></option>
                    <?php } ?>
                    </select>
                </td>
                <td>code client</td>
                <td>
                    
                    <select id="num_client" name="num_client">
                        <option>choisissez un code client</option>
                        <?php  foreach($this->infoCodeClient as $listeclient ){?>
                        <option data-nom ="<?php echo $listeclient['nom_client']?>" value="<?php echo $listeclient['code_client']?>"><?php echo substr($listeclient['code_client'],0,6)?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr> 
                <td>statut</td>
                <td><input type="text" name="statut" value="<?php echo $this->newetatvalidation['nom_etat_validation_xprev'] ?>"></td>
                <td>type de demande</td>
                <td>
                    <select required >
                        <option>choisissez un type de demande</option>
                    <?php foreach($this->listetypedemande as $listetype ){?>
                        <option><?php echo $listetype['nom_type_demande_xprev']?></option>
                    <?php } ?>
                    </select>
                </td>
                <td>nom client</td>
                <td><input type="text" id="nom_client" name="nom_client" value=""></td>
            </tr>
            <tr> 
                <td>émetteur prévision</td>
                <td><input type="text" name="emetteur" value="<?php echo $this->infoUser['nom_user'] ?>"></td>
                <td>date de début de prévision</td>
                <td><input required type="text" name="date_debut" id="date_debut" value=""></td>
                <td>code user</td>
                <td>
                    <select id="code_user" name="code_user">
                        <option></option>
                    </select>
                </td>
            </tr>
            <tr> 
                <td>commercial</td>
                <td><input type="text" name="commercial" value="<?php echo $this->infoUser['nom_user'] ?>"></td>
                <td>ajout de document</td>
                <td><input type="file" value="" name="fichierCreationXprev"></td>
                <td>nom user</td>
                <td><input id="nom_client_user" type="text" name="nom_client_user" value=""></td>
            </tr>

        </table>
        <p class="obligatoire">motif  de la demande :</p>
        <textarea name="motif_create" required cols="120" rows="7"> </textarea>
        <table id="table_mois" name="table_mois" class="enum" hidden="hidden">
            <thead>
            </thead>
            <tbody></tbody>
        </table>
        <p><button hidden="hidden" class="lesboutons" name="ajout_article" id="ajout_article">Ajouter une ligne</button></p>
        <div class="soumission">
            <input class="submit2" type="submit" value="valider la demande de prev">
        </div>
        
    </form>
</div>
