
<?php
$this->title = 'Xprev/creation';
$this->headTitle($this->title);
$this->headLink()->appendStylesheet('/css/jquery-ui.css');
$this->headScript()->appendFile('/js/controllers/xprev/datepicker2.js');

//<table style="display: none;" >
//    <tbody>
?><div class="contenu">
    <h2>Xprev</h2>
    <h3>extraction</h3>
    <form action="#" method="post">
        <table>
            <tr>
                <td>nom client</td>
                <td>
                    <select  name="nom_client">
                        <option value="">choisir un client</option>
                    <?php foreach($this->listeallclient as $listeclient ){?>
                    <option value="<?php echo $listeclient['code_user_client_xprev']?>" ><?php echo $listeclient['nom_client_xprev']; ?></option><?php }?>
                    </select>
                </td>
                <td>code client</td>
                <td>
                    <select  name="code_client">
                        <option value="">choisir un client</option>
                    <?php foreach($this->listeallclient as $listeclient ){?>
                    <option value="<?php echo $listeclient['code_user_client_xprev']?>" ><?php echo $listeclient['code_user_client_xprev']; ?></option><?php }?>
                    </select>
                </td>
                <td>code user</td>
                <td>
                    <select id="code_user" name="code_user">
                        <option></option>
                     <?php foreach($this->listeallclientuser as $listeclientuser ){?>
                    <option value="<?php echo $listeclientuser['code_client_users_xprev']?>" ><?php echo $listeclientuser['code_client_users_xprev']; ?></option><?php }?>
                    </select>
                </td>
                <td>nom user</td>
                <td>
                    <select id="nom_user" name="nom_user">
                        <option></option>
                    <?php foreach($this->listeallclientuser as $listeclientuser ){?>
                    <option value="<?php echo $listeclientuser['code_client_users_xprev']?>" ><?php echo trim($listeclientuser['nom_client_user_xprev']); ?></option><?php }?>
                    </select>
                </td>
                
            </tr>
            <tr>
                <td>nom commercial</td>
                <td>
                    <select name="nom_commercial">
                        <option value="">choisir un commercial</option>
                    <?php foreach($this->listeallcommercial as $listecommercial ){?>
                    <option value="<?php echo $listecommercial['id_commercial']?>"><?php echo $listecommercial['nom_commercial']; ?></option><?php }?>
                    </select>
                </td>
                <td>recherche par émetteur</td>
                <td>
                    <select name="nom_emetteur">
                        <option value="">choisir un émetteur</option>
                    <?php foreach($this->listealluser as $listeuser ){?>
                    <option value="<?php echo $listeuser['id_emetteur']?>" ><?php echo $listeuser['nom_emetteur']; ?></option><?php }?>
                   </select>
                </td>
                <td> statut</td>
                <td>
                    <select  name="nom_statut">
                        <option value="">choisir un statut</option>
                    <?php foreach($this->listeallstatut as $listestatut ){?>
                    <option value="<?php echo $listestatut['id_statut_xprev']?>" ><?php echo $listestatut['nom_statut_xprev']; ?></option><?php }?>
                   </select>
                </td>
            </tr>
            <tr>
                <td> date de création</td>
                <td>du <input class="datePicker" type="text" name="date_createdeb_prev" id='datepicker1'></td>
                <td>au <input class="datePicker" type="text" name="date_createfin_prev" id='datepicker2'></td>
            </tr>
            <tr>
                
                <td>référence article</td>
                <td>
                    <select  name="reference">
                        <option value="">choisir une référence</option>
                    <?php foreach($this->listeallreference as $listereference ){?>
                    <option value="<?php echo $listereference['reference_article']?>"  ><?php echo $listereference['reference_article']; ?></option><?php }?>
                   </select>
                </td>
                <td>code article</td>
                <td>
                    <select  name="code_article">
                        <option value="">choisir un code article</option>
                    <?php foreach($this->listeallcode as $listecode ){?>
                    <option value="<?php echo $listecode['code_article']?>"  ><?php echo $listecode['code_article']; ?></option><?php }?>
                   </select>
                </td>
           </tr>
            <tr>
                <td> date de début prévision</td>
                <td>du <input class="datePicker" type="text" name="date_debdeb_prev" id='datepicker3'></td>
                <td>au <input class="datePicker" type="text" name="date_debfin_prev" id='datepicker4'></td>
                <td> date de fin prévision</td>
                <td>du <input class="datePicker" type="text" name="date_debfin_prev" id='datepicker5'></td>
                <td>au <input class="datePicker" type="text" name="date_infin_prev" id='datepicker6'></td>
                <td></td>
            </tr>
        </table>
        <div class="soumission">
                <input class="submit2" type="submit" value="extraire">
        </div>
    </form>
    