<?php
$this->title = 'Xdistrib/accueil';
$this->headTitle($this->title);
?>
<div class="contenu">
    <h2>Xprev</h2>
    <h3>Demande de prévision en ligne </h3>
    <table class="enum">
        <tr>
            <?php if(in_array($this->fonction,$this->fn0)){?>
            
            <th>Tracking</th>
            <th>Date de création</th>
            <th>Emetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <?php foreach($this->listexprev as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_user'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a>
             </td>
                </tr>
                 <?php } ?>
        <?php }
        elseif( in_array($this->fonction,$this->fn1) ){?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>Emetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <?php foreach($this->listexprev as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_user'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a>
             </td>
             
                </tr>
                 <?php } ?>
        <?php }
        elseif(in_array($this->fonction, $this->fn2)) {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <th>validation</th>
             <?php foreach($this->listeN1xprev as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_user'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a>
             </td>
             <?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='validation N+1' ){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validn1","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a></td>
                </tr><?php }} ?>
         <?php } 
         elseif(in_array($this->fonction, $this->fn2bis)) {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <th>validation</th>
             <?php foreach($this->listeRegxprev as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_user'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a></td>
                    <?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='validation N+1' ){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validn1","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a></td>
                </tr>
                    <?php } } ?>
         <?php } 
         elseif(in_array($this->fonction, $this->fn3) && $this->fonction !='50') {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <th>validation</th>
             <?php foreach($this->listeAllxprev as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_user'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a></td>
                    <?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='validation logistique' ){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validlog","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a></td>
                </tr>
                    <?php }elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='validation dop' && $this->fonction =='50'){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validdop","tracking"=>$xprev['tracking'])); ?>" <button class="retour">validation</button></a></td>
                </tr>
                    <?php } elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='traitement' ){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"traitement","tracking"=>$xprev['tracking'])); ?>" <button class="retour">traiter</button></a></td>
                </tr>
                    <?php }elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='traitée' && $this->fonction !='50'){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"cloture","tracking"=>$xprev['tracking'])); ?>" <button class="retour">cloturer</button></a></td>
                </tr>
                    <?php } } ?>
         <?php } elseif(in_array($this->fonction, $this->fn3) && $this->fonction =='50') {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <th>validation</th>
             <?php foreach($this->listeAllxprev as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_user'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a></td>
                    <?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='validation logistique' ){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validlog","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a></td>
                </tr>
                    <?php }elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='validation dop' && $this->fonction =='50'){ ?>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validdop","tracking"=>$xprev['tracking'])); ?>" <button class="retour">validation</button></a></td>
                </tr>
                    <?php }
                   } ?>
         <?php } ?>
         </tr>
    </table>
</div>
