<select id="code_user" name="code_user">
   
    <?php  foreach($this->listecodeuser as $listeclientuser ){
    if(count($listeclientuser) >1){ ?>
    <option selected="selected" data-nom ="<?php echo $listeclientuser['nom_client']?>" value="<?php echo $listeclientuser['code_client']?>"><?php echo $listeclientuser['code_client']; ?></option>
    <?php }else{ ?><option selected="selected" data-nom ="<?php echo $listeclientuser['nom_client']?>" value="<?php echo $listeclientuser['code_client']?>"><?php echo $listeclientuser['code_client']; ?></option><?php }} ?>
</select>