<thead>
    <tr>
        <th>référence</th>
        <th>code article</th>
        <?php foreach($this->tab as $val){ ?>
        <th><?php echo $val['month'].'/'.$val['year'] ?></th>
        <?php } ?>
    </tr>
</thead>
<tbody>
    <tr>
        <td><input type="text" name="reference" id="reference" value=""></td>
        <td><input type="text" name="code_article" id="code_article" value=""></td>
        <td><input type="text" name="m1" id="m1" value=""></td>
        <td><input type="text" name="m2" id="m2" value=""></td>
        <td><input type="text" name="m3" id="m3" value=""></td>
        <td><input type="text" name="m4" id="m4" value=""></td>
        <td><input type="text" name="m5" id="m5" value=""></td>
        <td><input type="text" name="m6" id="m6" value=""></td>
        <td><input type="text" name="m7" id="m7" value=""></td>
        <td><input type="text" name="m8" id="m8" value=""></td>
        <td><input type="text" name="m9" id="m9" value=""></td>
        <td><input type="text" name="m10" id="m10" value=""></td>
        <td><input type="text" name="m11" id="m11" value=""></td>
        <td><input type="text" name="m12" id="m12" value=""></td>
    </tr>
</tbody>