<?php if(count($this->listecodeuser) >1){ ?>
<select id="code_user" name="code_user">
   
    <?php  foreach($this->listecodeuser as $listeclientuser ){ ?>
    <option  data-nom ="<?php echo $listeclientuser['nom_client']?>" value="<?php echo $listeclientuser['code_client']?>"><?php echo $listeclientuser['code_client']; ?></option>
<?php }?>
</select>
    <?php  }else { ?> }
        <input type="text" value="<?php echo $listeclientuser['code_client']?>">
        <?php  } ?>