<?php
$this->title = 'Xprev/recherche';
$this->headTitle($this->title);
$this->headLink()->appendStylesheet('/css/jquery-ui.css');
$this->headScript()->appendFile('/js/controllers/xprev/datepicker2.js');
?>
<div class="contenu">
    <h2>Xprev</h2>
    <h3>Recherche</h3>
    <form action="#" method="post">
        <table>
            <tr>
                <td>recherche par client</td>
                <td>
                    <select  name="nom_client">
                        <option value="">choisir un client</option>
                    <?php foreach($this->listeallclient as $listeclient ){?>
                    <option value="<?php echo $listeclient['code_client_users_xprev']?>" ><?php echo $listeclient['nom_client_user_xprev']; ?></option><?php }?>
                    </select>
                </td>
                <td>recherche par commercial</td>
                <td>
                    <select name="nom_commercial">
                        <option value="">choisir un commercial</option>
                    <?php foreach($this->listeallcommercial as $listecommercial ){?>
                    <option value="<?php echo $listecommercial['id_commercial']?>"><?php echo $listecommercial['nom_commercial']; ?></option><?php }?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>recherche par statut</td>
                <td>
                    <select  name="nom_statut">
                        <option value="">choisir un statut</option>
                    <?php foreach($this->listeallstatut as $listestatut ){?>
                    <option value="<?php echo $listestatut['id_statut_xprev']?>" ><?php echo $listestatut['nom_statut_xprev']; ?></option><?php }?>
                   </select>
                </td>
                <td>recherche par émetteur</td>
                <td>
                    <select name="nom_emetteur">
                        <option value="">choisir un émetteur</option>
                    <?php foreach($this->listealluser as $listeuser ){?>
                    <option value="<?php echo $listeuser['id_emetteur']?>" ><?php echo $listeuser['nom_emetteur']; ?></option><?php }?>
                   </select>
                </td>
            </tr>
            
            <tr>
                <td> date de création</td>
                <td>du <input class="datePicker" type="text" name="date_createdeb_prev" id='datepickerOO'></td>
                <td>au <input class="datePicker" type="text" name="date_createfin_prev" id='datepickerO'></td>
            </tr>
            <tr>
                
                <td>recherche par référence article</td>
                <td>
                    <select  name="reference">
                        <option value="">choisir une référence</option>
                    <?php foreach($this->listeallreference as $listereference ){?>
                    <option value="<?php echo $listereference['reference_article']?>"  ><?php echo $listereference['reference_article']; ?></option><?php }?>
                   </select>
                </td>
            </tr>
            <tr>
                <td>recherche par tracking</td>
                <td>
                    <select  name="tracking">
                        <option value="">choisir un tracking</option>
                    <?php foreach($this->listealltracking as $listetracking ){?>
                    <option value="<?php echo $listetracking['tracking']?>"  ><?php echo $listetracking['tracking']; ?></option><?php }?>
                   
                    </select>
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <div class="soumission">
                <input class="submit2" type="submit" value="rechercher">
        </div>
    </form>
    <?php if(!empty($this->formData)){ ?>
         <table class="enum">
        <tr>
            <?php if(in_array($this->fonction,$this->fn0)){?>
            
            <th>Tracking</th>
            <th>Date de création</th>
            <th>Emetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>action</th>
             <?php foreach($this->formdata as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_emetteur'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a>
             </td>
                </tr>
                 <?php } ?>
        <?php }
        elseif( in_array($this->fonction,$this->fn1) ){?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>Emetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th>consultation</th>
             <?php foreach($this->formdata as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_emetteur'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a>
             </td>
             
                </tr>
                 <?php } ?>
        <?php }
        elseif(in_array($this->fonction, $this->fn2)) {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th colspan="2">action</th>
             <?php foreach($this->formdata as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_emetteur'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a>
             </td>
             <td>
             <?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='en cours de validation N+1' ){ ?>
                    <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validn1","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a>
             <?php } ?>  </td>
                </tr><?php } ?>
         <?php } 
         elseif(in_array($this->fonction, $this->fn2bis)) {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th colspan="2">action</th>
             <?php foreach($this->formdata as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_emetteur'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a></td>
                    <td>
                        <?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='en cours de validation N+1' ){ ?>
                    <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validn1","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a></td>
                <?php } ?>  </td>
                </tr>
                    <?php  } ?>
         <?php } 
         elseif(in_array($this->fonction, $this->fn3) && $this->fonction !='50') {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th colspan="2">action</th>
             <?php foreach($this->formdata as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_emetteur'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a></td>
                    
                        <td><?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='en cours de validation logistique' ){ ?>
                    <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validlog","tracking"=>$xprev['tracking']));?>" <button class="retour">validation</button></a></td>
                </tr><td>
                    <?php }elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='en cours de validation dop' && $this->fonction =='50'){ ?>
                    <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validdop","tracking"=>$xprev['tracking'])); ?>" <button class="retour">validation</button></a></td>
                </tr><td>
                    <?php } elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='en cours de traitement' ){ ?>
                    <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"traitement","tracking"=>$xprev['tracking'])); ?>" <button class="retour">traiter</button></a></td>
                </tr><td>
                    <?php }elseif($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='traitée' && $this->fonction !='50'){ ?>
                    <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"cloture","tracking"=>$xprev['tracking'])); ?>" <button class="retour">modifier</button></a></td>
                <?php } ?>  </td>
    </tr>
                    <?php  } ?>
         <?php } elseif(in_array($this->fonction, $this->fn3) && $this->fonction =='50') {?>
            <th>Tracking</th>
            <th>Date de création</th>
            <th>émetteur</th>
            <th>Commercial</th>
            <th>Client</th>
             <th>Statut</th>
             <th colspan="2">action</th>
             <?php foreach($this->formdata as $xprev){ ?>
                <tr>
                    <td><?php echo $xprev['tracking'] ?></td>
                    <td><?php echo $xprev['date_create'] ?></td>
                    <td><?php echo $xprev['nom_emetteur'] ?></td>
                    <td><?php echo $xprev['nom_commercial'] ?></td>
                    <td><?php echo $xprev['nom_client_user_xprev'] ?></td>
                    <td><?php echo $xprev['nom_validation_xprev'] ?></td>
                    <td><a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"consult","tracking"=>$xprev['tracking']));?>" <button class="retour">historique</button></a></td>
                    <td><?php if($xprev['nom_validation_xprev']!='refusée' && $xprev['nom_validation_xprev']=='en cours de validation dop' && $this->fonction =='50'){ ?>
               <a href="<?php echo $this->url(array("controller"=>"xprev","action"=>"validdop","tracking"=>$xprev['tracking'])); ?>" <button class="retour">validation</button></a></td>
                 <?php } ?>  </td>
    </tr>
                    <?php 
                   } ?>
         <?php } ?>
         </tr>
             <?php  } ?>
        </table>
</div>
