<div class="contenu">
    <h2>Xprev</h2>
    <h3>Recherche</h3>
    <form>
        <table>
            <tr>
                <td>recherche par client</td>
                <td>
                    <select  name="nom_client">
                    <?php foreach($this->listeallclient as $listeclient ){?>
                    <option value="<?php echo $listeclient['code_client_user_xprev']?>" ><?php echo $listeclient['nom_client_xprev'];}?></option>
                    </select>
                </td>
                <td>recherche par commercial</td>
                <td>
                    <select name="nom_commercial">
                    <?php foreach($this->listeallcommercial as $listecommercial ){?>
                    <option value="<?php echo $listecommercial['id_commercial']?>"><?php echo $listecommercial['nom_commercial'];}?></option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>recherche par statut</td>
                <td>
                    <select  name="nom_statut">
                    <?php foreach($this->listeallstatut as $listestatut ){?>
                    <option value="<?php echo $listestatut['id_statut_xprev']?>" ><?php echo $listestatut['nom_statut_xprev'];}?></option>
                   </select>
                </td>
                <td>recherche par émetteur</td>
                <td>
                    <select name="nom_emetteur">
                    <?php foreach($this->listealluser as $listeuser ){?>
                    <option value="<?php echo $listeuser['id_emetteur']?>" ><?php echo $listeuser['nom_emetteur'];}?></option>
                   </select>
                </td>
            </tr>
            <tr>
                <td>recherche par date de création</td>
                <td></td>
                <td>recherche par référence article</td>
                <td>
                    <select  name="reference">
                    <?php foreach($this->listeallreference as $listereference ){?>
                    <option value="<?php echo $listereference['reference_article']?>"  ><?php echo $listereference['reference_article'];}?></option>
                   </select>
                </td>
            </tr>
            <tr>
                <td>recherche par tracking</td>
                <td>
                    <select  name="tracking">
                    <?php foreach($this->listealltracking as $listetracking ){?>
                    <option value="<?php echo $listetracking['id_demande_xprev']?>"  ><?php echo $listetracking['tracking'];}?></option>
                   
                    </select>
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <div class="soumission">
                <input class="submit2" type="submit" value="rechercher">
        </div>
    </form>
    
</div>