<div class="contenu">
    <h2>Xprev</h2>
    <h3>Demande d'information complémentaire de la logistique pour la demande de prev: <?php echo $this->infoPrev['tracking'] ;?> </h3>
    <fieldset class="field">
        <legend>Informations générales</legend>
        <table id="information3">
            <tr> 
                <td>date de création</td>
                <td><?php echo $this->infoPrev['date_create'] ;?></td>
                <td>niveau de risque</td>
                <td><?php echo $this->infoPrev['nom_risque_xprev'] ;?></td>
                <td>code client</td>
                <td><?php echo $this->infoPrev['code_user_client_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>statut</td>
                <td><?php echo $this->infoPrev['nom_validation_xprev'] ;?></td>
                <td>type de demande</td>
                <td><?php echo $this->infoPrev['nom_type_demande_xprev'] ;?></td>
                <td>nom client</td>
                <td><?php echo $this->infoPrev['nom_client_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>émetteur prévision</td>
                <td><?php echo $this->infoPrev['nom_user'] ;?></td>
                <td>date de début de prévision</td>
                <td><?php echo $this->infoPrev['date_debut'] ;?></td>
                <td>code user</td>
                <td><?php echo $this->infoPrev['code_client_users_xprev'] ;?></td>
            </tr>
            <tr> 
                <td>commercial</td>
                <td><?php echo $this->infoPrev['nom_commercial'] ;?></td>
                <td></td>
                <td></td>
                <td>nom user</td>
                <td><?php echo $this->infoPrev['nom_client_user_xprev'] ;?></td>
            </tr>
        </table>
        
        <p>motif  de la demande :<?php echo $this->infoPrev['justification'] ;?></p>
        <?php if( $this->infoPrev['justification_n1']!= null) { ?>
        <p>commentaire n+1 :<?php echo $this->infoPrev['justification_n1'] ;?></p>
        <?php } ;?>
        <?php if( $this->infoPrev['justification_log']!= null) { ?>
        <p>commentaire logistique :<?php echo $this->infoPrev['justification_log'] ;?></p>
        <?php } ;?>
        
        <p class="decale">fichier joint :<?php foreach ($this->infoFichier as $fichier){ ?> <a class="fichier_joint" href=" <?php echo $fichier['chemin_fichier_xprev']; ?>" target="_blank"><?php echo $fichier['nom_fichier_xprev']; ?></a><br><?php  }?></p>
    </fieldset>
    <fieldset class="field">
        <legend>Informations article</legend>
        <table class="enum">
            <thead>
                <tr>
                    <th>référence</th>
                    <th>code article</th>
                     <?php if($this->infoUser['niveau']=='niveau4'){ ;?>
                    <th>prix de revient</th>
                    <th>shikomi</th>
                    <?php }?>
                    <?php foreach ($this->infoMois as $mois){ ?>
                    <th><?php echo $mois['month'] ."/".$mois['year']?></th><?php }?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->infoArticle as $article){ ?>
                <tr>
                    <td style="width: 250px;"><?php echo $article['reference_article'] ;?></td>
                    <td><?php echo $article['code_article'] ;?></td>
                    <?php if($this->infoUser['niveau']=='niveau4'){ ;?>
                    <td></td>
                    <td></td>
                    <?php }?>
                    <td><?php echo $article['m1'] ;?></td>
                    <td><?php echo $article['m2'] ;?></td>
                    <td><?php echo $article['m3'] ;?></td>
                    <td><?php echo $article['m4'] ;?></td>
                    <td><?php echo $article['m5'] ;?></td>
                    <td><?php echo $article['m6'] ;?></td>
                    <td><?php echo $article['m7'] ;?></td>
                    <td><?php echo $article['m8'] ;?></td>
                    <td><?php echo $article['m9'] ;?></td>
                    <td><?php echo $article['m10'] ;?></td>
                    <td><?php echo $article['m11'] ;?></td>
                    <td><?php echo $article['m12'] ;?></td>
                </tr>
                <?php  }?>
            </tbody>
        </table>
    </fieldset>
    <form action="#" method="post" enctype="multipart/form-data">
        
        <fieldset class="field">
            <legend>supplément d'information </legend>
            <fieldset class="field">
                <legend>demande de la logistique</legend>
                <?php foreach($this->infodemandelog as $infologdemande){ ;?>
                
                 <?php if($infologdemande['reponse_infolog']!= null){?>
                <p>demande de la log :<?php echo  $infologdemande['demande_infolog']?></p>
                <p>réponse: <?php echo  $infologdemande['reponse_infolog']?></p>
                     <?php  } else { ?>
                <fieldset class="field">
                    <p>demande de la log :<?php echo  $infologdemande['demande_infolog']?></p>
                    <input hidden="hidden" value="<?php echo  $infologdemande['id_infolog']?>" name="id_infolog">
                    <legend>réponse</legend>
                    <textarea required name="supplement" cols="120" rows="7" value=""></textarea>
                     <p>Ajout de document : <input type="file" value="" name="fichierSupplogXprev"></p>
                  </fieldset>
                         <?php  }  ?>
                <?php  }?>
            </fieldset>
            
            <div class="soumission">
                <input class="submit2" type="submit" value="valider">
            </div>
             
        </fieldset>
    </form>
</div>