<?php
$this->title = 'Accueil';
$this->headTitle($this->title);
?>
<div id="accueil" class="contenu">
    <img src="/images/newAccueil.png" alt="" usemap="#Map" style="padding-left: 50px;" />
    <map name="Map" id="Map">
    <area alt="xprice" title="xprice" href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'index'), null, true); ?>" shape="poly" coords="10,179,92,176,92,263,7,266" />
    <area alt="xdistrib" title="xdistrib" href="<?php echo $this->url(array('controller' => 'xdistrib', 'action' => 'index'), null, true); ?>" shape="poly" coords="105,94,198,96,199,195,109,197" />
    <area alt="" title="" href="#" shape="poly" coords="354,3,461,5,453,93,364,102" />
    <area alt="" title="" href="#" shape="poly" coords="490,20,580,23,582,122,487,132" />
    <area alt="" title="" href="#" shape="poly" coords="616,95,711,97,698,185,604,196" />
    <area alt="" title="" href="#" shape="poly" coords="718,168,800,168,798,255,709,267" />
    <area alt="" title="" href="#" shape="poly" coords="467,142,471,268,351,264,344,144" />
    </map>
</div>
