<?php
$this->title = 'Accueil';
$this->headTitle($this->title);
?>
<div id="accueil" class="contenu">
    <img class="imgindex" src="/images/newAccueil.png" alt="" usemap="#Map" style="padding-left: 50px;" />
    <map name="Map" id="Map" class="imgindex">
    <area alt="xprice" title="xprice" href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'index'), null, true); ?>"  shape="circle" coords="100,213,50" />
    <area alt="xdistrib" title="xdistrib" href="<?php echo $this->url(array('controller' => 'xdistrib', 'action' => 'index'), null, true); ?>" shape="circle" coords="200,143,50" />
    <area alt="" title="" href="#" shape="circle" coords="327,68,50" />
    <area alt="" title="" href="#" shape="circle" coords="449,53,50" />
    <area alt="" title="" href="#" shape="circle" coords="579,68,50" />
    <area alt="" title="" href="#" shape="circle" coords="699,143,50" />
    <area alt="" title="" href="#" shape="circle" coords="800,213,50" />
    </map>
</div>
