<?php
$this->title = 'Accueil';
$this->headTitle($this->title);
?>
<div id="accueil" class="contenu">
    <img src="/images/accueilXsuite_1.png" alt="" usemap="#Map" style="padding-left: 50px;" />
    <map name="Map" id="Map">
    <area alt="xprice" title="xprice" <a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'index'), null, true); ?>" shape="poly" coords="161,49,275,48,270,146,163,149"  /> 
    <area alt="" title="" href="#" shape="poly" coords="9,175,125,172,123,268,10,266" />
    <area alt="" title="" href="#" shape="poly" coords="150,185,262,190,266,291,157,289" />
    <area alt="" title="" href="#" shape="poly" coords="418,15,533,17,530,114,435,116" />
    <area alt="" title="" href="#" shape="poly" coords="456,154,575,156,578,256,462,259" />
    <area alt="" title="" href="#" shape="poly" coords="574,20,684,19,681,135,571,135" />
    </map>
</div>
