
<div class="adminupdate">
    <table class="enum">
        <tr>
            <td colspan="2"><img width="150" height="150" style="margin-left: 75px;" src="/images/Avatar.png"></td>
        </tr>
        <tr>
            <td>Nom :</td>
            <td><?php echo $this->utilisateur['nom_user'];?></td>
        </tr>
         <tr>
            <td>Prénom :</td>
            <td><?php echo $this->utilisateur['prenom_user'];?></td>
        </tr>
         <tr>
            <td>Téléphone :</td>
            <td><?php echo $this->utilisateur['tel_user'];?></td>
        </tr>
         <tr>
            <td>Mail :</td>
            <td><?php echo $this->utilisateur['email_user'];?></td>
        </tr>
         <tr>
            <td>Numéro user workplace :</td>
            <td><?php echo $this->utilisateur['numwp_user'];?></td>
        </tr>
         <tr>
            <td>Fonction :</td>
            <td><?php echo $this->fonction['description_fonction'] ;?></td>
        </tr>
         <tr>
            <td>Zone :</td>
            <td><?php echo $this->zone['nom_zone'];?></td>
        </tr>
         <tr>
            <td>Holon :</td>
            <td><?php echo $this->holon['nom_holon'] ;?></td>
        </tr>
    </table>
</div