<div class="adminupdate">
    <table class="enum">
        <tr>
            <td>Nom de l'industrie:</td>
            <td><?php  echo $this->industry['nom_industry'];?><input hidden="hidden" name="industry" value="<?php echo $industrys['id_industry']?>"/></td>
        </tr>
        <tr>
            <td>code smc de l'industrie:</td>
            <td><?php  echo $this->industry['nom_industry'];?></td>
        </tr>
        <tr>
            <td>code movex de l'industrie:</td>
            <td><?php  echo $this->industry['nom_industry'];?></td>
        </tr>
        <tr>
            <td>Description de l'industrie:</td>
            <td><?php  echo $this->fonction['description_industry'];?></td>
        </tr>
    </table>
</div>