<div class="adminupdate">
    <table class="enum">
        <tr>
            <td>Nom de la fonction:</td>
            <td><?php  echo $this->fonction['nom_fonction'];?><input hidden="hidden" name="fonction" value="<?php echo $fonctions['id_fonction']?>"/></td>
        </tr>
        <tr>
            <td>Description de la fonction:</td>
            <td><?php  echo $this->fonction['description_fonction'];?></td>
        </tr>
    </table>
</div>