<!--
<div class="adminupdate">
    <table class="enum">
        <tr>
            <td colspan="2"><img width="150" height="150" style="margin-left: 75px;" src="/images/Avatar.png"></td>
        </tr>
        <tr>
            <td>Nom :</td>
            <td><?php //  echo $this->utilisateur['nom_user'];?></td>
        </tr>
         <tr>
            <td>Prénom :</td>
            <td><?php //  echo $this->utilisateur['prenom_user'];?></td>
        </tr>
         <tr>
            <td>Téléphone :</td>
            <td><?php //  echo $this->utilisateur['tel_user'];?></td>
        </tr>
         <tr>
            <td>Mail :</td>
            <td><?php //  echo $this->utilisateur['email_user'];?></td>
        </tr>
         <tr>
            <td>Numéro user workplace :</td>
            <td><?php //  echo $this->utilisateur['numwp_user'];?></td>
        </tr>
         <tr>
            <td>Fonction :</td>
            <td><?php //  echo $this->fonction['description_fonction'] ;?></td>
        </tr>
         <tr>
            <td>Zone :</td>
            <td><?php //  echo $this->zone['nom_zone'];?></td>
        </tr>
         <tr>
            <td>Holon :</td>
            <td><?php //  echo $this->holon['nom_holon'] ;?></td>
        </tr>
    </table>
</div>-->

<div>
    <div style="float: left; width: 300px;">
        <span style="text-align:left; float: left; width:250px; "><h6>Expéditeur :</h6><br/></span>
       <table>
        <tr>
            <td>Société :</td>
            <td><?php echo $societe ?></td>
        </tr>
        <tr>
            <td>Adresse :</td>
            <td><?php echo $adresse ?></td>
        </tr>
        <tr>
            <td>Code postal :</td>
            <td><?php echo $code_postal ?></td>
        </tr>
        <tr>
            <td>Ville :</td>
            <td><?php echo $ville ?></td>
        </tr>
        <tr>
            <td>Nom du contact :</td>
            <td><?php echo $contact ?></td>
        </tr>
        <tr>
            <td>Email :</td>
            <td><?php echo $email ?></td>
        </tr>
         <tr>
            <td>Tel :</td>
            <td><?php echo $tel ?></td>
        </tr>
         <tr>
            <td>Fax :</td>
            <td></td>
        </tr>
    </table> 
    </div>
    <div style="float:right;width: 300px;">
        <span style="text-align:left; float: right; width:250px; "><h6>Adresse de livraison :</h6></span>
        <table>
            <tr>
                <td>SMC PNEUMATIQUE SA</td>
            </tr>
            <tr>
                <td>Support Technique</td>
            </tr>
            <tr>
                <td>1, boulevard de Strasbourg</td>
            </tr>
            <tr>
                <td>Parc Gustave Eiffel</td>
            </tr>
            <tr>
                <td>77160 BUSSY SAINT GEORGES</td>
            </tr>
            <tr>
                <td>Tel : 01 64 76 21 65</td>
            </tr>
            <tr>
                <td>Email : support-technique@smc-france.fr</td>
            </tr>
        </table>
    </div>
    <div>
        <table>
            <tr>
                <td>N° Dossier :</td>
                <td></td>
            </tr>
            <tr>
                <td> N° Retour Client : </td>
                <td></td>
            </tr>
            <tr>
                <td>référence produit:</td>
                <td></td>
            </tr>
            <tr>
                <td>Code fabrication :</td>
                <td></td>
            </tr>
            <tr>
                <td>N° de facture :</td>
                <td></td>
            </tr>
            <tr>
                <td>Problèmes rencontrés :</td>
                <td></td>
            </tr>
            <tr>
                <td>Quantité :</td>
                <td></td>
            </tr>
        </table>
    </div>
</div>