
<div id="admin_contenu">
       <h1>Cr&eacute;ation d'un utilisateur</h1>
       <div>
           <table>
               <tr>
                   <td colspan="2"><img width="100" height="100"  src="/images/Avatar.png"></td>
               </tr>
               <tr>
                   <td>Nom</td>
                   <td><input type="text" name="nom" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>prénom</td>
                   <td><input type="text" name="prenom" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Téléphone</td>
                   <td><input type="text" name="tel" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Email</td>
                   <td><input type="text" name="email" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Zone</td>
                   <td><input type="text" name="zone" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Holon</td>
                   <td><input type="text" name="holon" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Fonction</td>
                   <td><input type="text" name="fonction" class="inputFormUser"/></td>
               </tr>
           </table>
       </div>
    </div>
