
<div id="admin_contenu">
       <h1>Cr&eacute;ation d'un utilisateur</h1>
       <div id="imgcreateUser"><img width="100" height="100"  src="/images/Avatar.png"></div>
       <div id="createUserRight">
           <form id="formcreateuser">
           <table class="createuser">
               <tr>
                   <td>Nom</td>
                   <td><input type="text" name="nom" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>prénom</td>
                   <td><input type="text" name="prenom" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Téléphone</td>
                   <td><input type="text" name="tel" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Email</td>
                   <td><input type="text" name="email" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Zone</td><td>Fonction</td><td>Holon</td>
               </tr>
               <tr>
                   <td><select  name="zone" ></select></td>
                   <td><select  name="fonction" ></select></td>
                   <td><select  name="holon" ></select></td>
               </tr>
           </table>
           </form>
       </div>

    </div>
