<div id="admin_contenu">
    <h2>Cr&eacute;ation d'un holon</h2>
    <div id="createHolonRight">
        <form id="formcreateholon" method="post">
            <table class="">
                <tr>
                    <td>Nom de l'holon:</td>
                    <td><input type="text" name="nom_holon" class="inputFormHolon"/></td>
                </tr>
                <tr>
                    <td>description de l'holon:</td>
                    <td><textarea name="description_holon"></textarea></td>
                </tr>
            </table>
            <input id="creerholon" class="submit" type="submit" value="créer">
        </form>
    </div>
</div>