<div id="admin_contenu">
    <h2>Cr&eacute;ation d'une zone</h2>
    <div id="createZoneRight">
        <form id="formcreatezone" method="post">
            <table class="">
                <tr>
                    <td>Nom de la zone:</td>
                    <td><input type="text" name="nom_zone" class="inputFormZone"/></td>
                </tr>
                <tr>
                    <td>description de la zone:</td>
                    <td><textarea name="description_zone"></textarea></td>
                </tr>
            </table>
            <input id="creerzone" class="submit" type="submit" value="créer">
        </form>
    </div>
</div>