
<div id="admin_contenu">
    <h2>Cr&eacute;ation d'un utilisateur</h2>
       <div id="imgcreateUser"><img width="100" height="100"  src="/images/Avatar.png"></div>
       <div id="createUserRight">
           <form id="formcreateuser" method="post">
           <table class="createuser">
               <tr>
                   <td>Nom</td>
                   <td><input type="text" name="nom" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Prénom</td>
                   <td><input type="text" name="prenom" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Téléphone</td>
                   <td><input type="text" name="tel" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Email</td>
                   <td><input type="text" name="email" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Matricule</td>
                   <td><input type="text" name="matricule" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>User Workplace</td>
                   <td><input type="text" name="userworkplace" class="inputFormUser"/></td>
               </tr>
               <tr>
                   <td>Zone</td><td>Fonction</td><td>Holon</td>
               </tr>
               <tr>
                   <td><select  name="zone" ><?php foreach($this->listZone as $value){; ?><option value="<?php echo $value['id_zone'];?>"><?php echo $value['nom_zone'];?></option><?php }; ?></select></td>
                   <td><select  name="fonction" ><?php foreach($this->listFonction as $value){; ?><option value="<?php echo $value['id_fonction'];?>"><?php echo $value['nom_fonction'].'('.$value['description_fonction'].')';?></option><?php }; ?></select></td>
                   <td><select  name="holon" ></select></td>
               </tr>
           </table>
                <input id="creeruser" class="submit" type="submit" value="créer">
           </form>
       </div>

    </div>
