<div id="admin_contenu">
    <h2>Cr&eacute;ation d'une fonction</h2>
    <div id="createFonctionRight">
        <form id="formcreatefonction" method="post">
            <table class="">
                <tr>
                    <td>Nom de la fonction:</td>
                    <td><input type="text" name="nom_fonction" class="inputFormFonction"/></td>
                </tr>
                <tr>
                    <td>description de la fonction</td>
                    <td><textarea name="description_fonction"></textarea></td>
                </tr>
            </table>
            <input id="creerfonction" class="submit" type="submit" value="créer">
        </form>
    </div>
</div>