<div id="admin_contenu">
    <h2>Cr&eacute;ation d'une industrie</h2>
    <div id="createIndustryRight">
        <form id="formcreateindustry" method="post">
            <table class="">
                <tr>
                    <td>Nom de l'industrie:</td>
                    <td><input type="text" name="nom_industry" class="inputFormIndustry"/></td>
                </tr>
                <tr>
                    <td>code smc de l'industrie:</td>
                    <td><input type="text" name="code_smc_industry" class="inputFormIndustry"/></td>
                </tr>
                <tr>
                    <td>code movex  de l'industrie:</td>
                    <td><input type="text" name="code_movex_industry" class="inputFormIndustry"/></td>
                </tr>
                <tr>
                    <td>description de l'industrie:</td>
                    <td><textarea name="description_industry"></textarea></td>
                </tr>
            </table>
            <input id="creerindustry" class="submit" type="submit" value="créer">
        </form>
    </div>
</div>