<div class="">
    <div id="createuserdiv" >
        <a href="<?php echo $this->url(array("controller"=>"administration","action"=>"createuser"));?>" <button class="retour" id="createusera">Création d'un utilisateur</button></a>
    </div>

    <div id="modifconsultdiv">
        <table>
            <?php foreach($this->malisteUser as $key=>$users){ ?>
            <tr>
                <td><?php echo $users['nom_user'] ?></td>
                <td><?php echo $users['prenom_user'] ?><input hidden="hidden" name="user" value="<?php echo $users['id_user']?>"/></td>
            <td><a href="<?php echo $this->url(array("controller"=>"administration","action"=>"consultuser","user"=>$users['id_user']));?>" <button class="retour" id="consultation-<?php echo $k; ?>">consultation</button></a></td>
                <td><a href="<?php echo $this->url(array("controller"=>"administration","action"=>"updateuser","user"=>$users['id_user']));?>" <button class="retour" id="modification-<?php echo $k; ?>">modification</button></a></td>
        </tr><?php } ?>
        </table>
    </div>
</div>