<div class="">
    <fieldset>
        <legend>Région Nord</legend>
        <table>
            <thead>
                <tr>
                    <th>holon</th>
                    <th>nom</th>
                    <th>fonction</th>
                    <th>action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->listehierarchie as $list){ ?>
               
                    <tr>
                        <td><?php echo $list['nom_holon'] ?></td>
                        <td><?php echo $list['nom_user'] ?></td>
                        <td><?php echo $list['nom_fonction'] ?></td>
                        <td><a href="<?php echo $list[''] ?>">modifier</a></td>
                    </tr>
                 <?php } ?>
            </tbody>
        </table>
    </fieldset>
</div>