<div class="">
    <fieldset>
        <legend>Région Nord</legend>
        <table class="enum">
            <thead>
                <tr>
                    <th>holon</th>
                    <th>nom</th>
                    <th>fonction</th>
                    <th>action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->listehierarchie as $list){ ?>
               
                    <tr>
                        <td><?php echo $list['nom_holon'] ?></td>
                        <td><?php echo $list['nom_user'] ?></td>
                        <td><?php echo $list['nom_fonction'] ?></td>
                        <td><a href="<?php echo $this->url(array("controller"=>"administration","action"=>"updatehierarchie","holon"=>$list['id_holon'],"fonction"=>$list['id_fonction']));?>" ><button class="retour">modification</button></a></td>
                    </tr>
                 <?php } ?>
            </tbody>
        </table>
    </fieldset>
</div>