<div class="adminupdate">
    <table class="enum">
        <tr>
            <td>Nom de l'industrie:</td>
            <td><input type="text" value="<?php  echo $this->industry['nom_industry'];?>"> <input hidden="hidden" name="industry" value="<?php echo $industrys['id_industry']?>"/></td>
        </tr>
        <tr>
            <td>code smc de l'industrie:</td>
            <td><select name="code_smc_industry"><?php foreach($this->listIndustry[0] as $listIndustry){?><option <?php if($listIndustry['id_industry'] == $this->industry['id_industry']){ ?> selected="selected" <?php }?> value ="<?php  echo $listIndustry['code_smc_industry'];?>"></option> <?php } ?></select></td>
        </tr>
        <tr>
            <td>code movex de l'industrie:</td>
            <td><?php  echo $this->industry['code_movex_industry'];?></td>
        </tr>
        <tr>
            <td>Description de l'industrie:</td>
            <td><?php  echo $this->industry['description_industry'];?></td>
        </tr>
    </table>
</div>