<div class="adminupdate">
    <table class="enum">
        <tr>
            <td>Nom de la zone:</td>
            <td><?php  echo $this->zone['nom_zone'];?><input hidden="hidden" name="zone" value="<?php echo $zones['id_zone']?>"/></td>
        </tr>
        <tr>
            <td>Description de la zone:</td>
            <td><?php  echo $this->zone['description_zone'];?></td>
        </tr>
    </table>
</div>