<div class="adminupdate">
    <table class="enum">
        <tr>
            <td>Nom de l'holon:</td>
            <td><?php  echo $this->holon['nom_holon'];?><input hidden="hidden" name="holon" value="<?php echo $holons['id_holon']?>"/></td>
        </tr>
        <tr>
            <td>Description de l'holon:</td>
            <td><?php  echo $this->holon['description_holon'];?></td>
        </tr>
    </table>
</div>