
<div class="adminupdate">
    <table class="enum">
        <tr>
            <td colspan="2"><img width="150" height="150" style="margin-left: 75px;" src="/images/Avatar.png"><input hidden="hidden" name="user" value="<?php echo $users['id_user']?>"/></td>
        </tr>
        <tr>
            <td>Nom :</td>
            <td><input type="text" value="<?php  echo $this->utilisateur['nom_user'];?>" name="nom_user"></td>
        </tr>
         <tr>
            <td>Prénom :</td>
            <td><input type="text" value="<?php  echo $this->utilisateur['prenom_user'];?>" name="prenom_user"></td>
        </tr>
         <tr>
            <td>Téléphone :</td>
            <td><input type="text" value="<?php  echo $this->utilisateur['tel_user'];?>" name="tel_user"></td>
        </tr>
         <tr>
            <td>Mail :</td>
            <td><input type="text" value="<?php  echo $this->utilisateur['email_user'];?>" name="email_user"></td>
        </tr>
         <tr>
            <td>Numéro user workplace :</td>
            <td><input type="text" value="<?php  echo $this->utilisateur['numwp_user'];?>" name="numwp_user"></td>
        </tr>
         <tr>
            <td>Fonction :</td>
            <td><select><?php foreach($this->listFonction as $listFonction){?><option<?php if($listFonction['id_fonction']==$this->fonction['id_fonction']){?> selected="selected" <?php }?> value="<?php echo $listFonction['id_fonction']?>"><?php echo $listFonction['nom_fonction']?></option><?php } ?></select><?php  echo $this->fonction['nom_fonction'] ;?></td>
        </tr>
         <tr>
            <td>Zone :</td>
            <td><?php  echo $this->zone['nom_zone'];?></td>
        </tr>
         <tr>
            <td>Holon :</td>
            <td><?php  echo $this->holon['nom_holon'] ;?></td>
        </tr>
    </table>
</div>