<?php 
$this->headScript()->appendFile('/js/jquery-1.10.2.min.js');
$this->headScript()->appendFile('/js/jquery-ui-1.10.4.min.js');
?>
<script>
     $(function() {
    var maliste=<?php echo json_encode($this->malisteUser); ?>
    $( "#user" ).autocomplete({
      source: maliste
    });
  });
</script>

 
<div class="ui-widget">
  <label for="user">Utilisateur: </label>
  <input id="user">
</div>