<div class="adminupdate">
    <form method="post">
        <table class="enum">
            <tr>
                <td>Nom de la zone:</td>
                <td><input hidden="hidden" name="zone" value="<?php echo $zones['id_zone']?>"/><input type="text" name="nom_zone" value="<?php  echo $this->zone['nom_zone'];?>"></td>
            </tr>
            <tr>
                <td>Description de la zone:</td>
                <td><textarea name="description_zone" value=""><?php  echo $this->zone['description_zone'];?></textarea></td>
            </tr>
        </table>
        <input id="updatezone" class="submit" type="submit" value="mettre à jour">
    </form>
</div>