<?php
$this->title = 'XSuite/Login';
$this->headTitle($this->title);
?>
<div id="loginne" class="contenu">
    <div id="formlogin" class="little_form">
        <p><h2>Identification</h2></p>
        <?php
        echo $this->form->setAction($this->url());
        ?>
    <span class="spanperdu"><a class="perdu" style="background-color: #268bd9;" href="<?php  echo $this->url(array('controller' => 'login', 'action' => 'perdu'), null, true); ?>">mot de passe perdu</a></span>
    </div>
</div>