<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <?php
        echo $this->headMeta();
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/global.css');
        echo $this->headTitle();
        ?>
        <script type="text/javascript" src="js/menu.js"></script>
        <script type="text/javascript" src="js/afficher.js"></script>

    </head>
    <body>
        <div id="header">
            <div id="header_left"><img  src="/images/smc_logo_2013.jpg" alt="" usemap="#Map2"/>
                <map name="Map2" id="Map2">
                    <area alt="accueil" title="accueil" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>" shape="rect" coords="11,10,223,50" />
                </map>
            </div>
            <div id="header_center"> <H1>Xsuite</H1></div>
            <div id="header_right">
                <div id="header_site">
                    <a href="">retour au site intranet</a>
                    <div id="logged-in-as"><?php echo $this->loggedInAs(); ?></div>
                </div>
            </div>
        </div>
        <div id="Content">
            <?php  $auth = Zend_Auth::getInstance(); echo $auth;?>
            <div id="menu_haut">
                <ul class="menu_haut">
                    <li><a>Xprice</a></li>
                    <li><a>Xprice Distrib</a></li>
                    <li><a>Xsimple</a></li>
                    <li><a>Xprev</a></li>
                    <li><a>Xpertise</a></li>
                    <li><a>XRFS</a></li>
                    <li><a>XSDB</a></li>
                    <li><a>Annuaire</a></li>
                </ul>
            </div>
<!--            <div id="sidebar_left">
                <ul  class="menu_entete" style ="padding-left:0px;padding-top: 5px;padding-bottom: 5px;">
                    <li class="menu_entete"><p class="title_menu">Xprice</p>
                        <ul class="sous_menu" style ="padding-left:0px;">
                            <li class="sous_menu"><a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'numwp'), null, true); ?>">Cr&eacute;ation</a></li>
                            <li class="sous_menu"><a href="<?php echo $this->url(array('controller' => 'xprice', 'action' => 'consult'), null, true); ?>">Consultation</a></li>
                        </ul>
                    </li>
                     <li class="menu_entete"><p class="title_menu">XPriceDistrib</p>
                        <ul>
                            <li></li>
                        </ul>
                    </li>
                    <li class="menu_entete"><p class="title_menu">XSimple</p>
                        <ul>
                            <li></li>
                        </ul>
                    </li>
                      <li class="menu_entete"><p class="title_menu">XPrev</p>
                        <ul>
                            <li></li>
                        </ul>
                    </li>
                     <li class="menu_entete"><p class="title_menu">XRFS</p>
                        <ul>
                            <li></li>
                        </ul>
                    </li>
                     <li class="menu_entete"><p class="title_menu">XSDB</p>
                        <ul>
                            <li></li>
                        </ul>
                    </li>
                     <li class="menu_entete"><p class="title_menu">XPertise</p>
                        <ul>
                            <li></li>
                        </ul>
                    </li>
                    <li class="menu_entete"><p class="title_menu">Annuaire utilisateur</p>
                        <ul class="sous_menu" style ="padding-left:0px;">
                            <li class="sous_menu"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'create'), null, true); ?>">Cr&eacute;ation</a></li>
                            <?php /*
                             * Si tu met un lien "modifier" ici il te faut une étape de sélection de l'entité à modifier
                             * sinon tu arrive sur un formulaire de modification vide.
                             */ ?>
                            <li class="sous_menu"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'update'), null, true); ?>">Modification</a></li>
                            <?php /* 
                             * Même remarque que ci dessus, hormis le fait que tu ne peux pas supprimer un élément non sélectionné.
                             */ ?>
                            <li class="sous_menu"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete'), null, true); ?>">Suppression</a></li>
                        </ul>
                    </li>
                </ul>
            </div>-->
            <div id="center">
                <?php if (count($this->messages)) : ?>
                    <ul id="messages">
                        <?php foreach ($this->messages as $message) : ?>
                            <li><?php echo $message; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <div id="footer">
            <div id="logo">
                <?php /* @todo commentaire franck
                 * Oulla ! attention au url relatives ça peut ne pas fonctionner partout !
                 * 2 solutions :
                 *  - utiliser une url absolue pour ce logo (src="/images/...)
                 *  - placer l'image en background css
                 */ ?>
            </div>
        </div>

    </body>
</html>
