
<h1>Utilisateurs</h1>
<?php 
$this->title ='utilisateurs Xsuite';
$this->headTitle($this->title);
?>
<div id="tableIndex">
    <form method="post" id="form_talent">
        <fieldset>
            <legend>Vos coordonn&eacute;es</legend>
            <table id="userIndex">
                <tr>
                    <td>Votre nom:</td>
                    <td><input type="text" name="nom" value="" id="nom"></td>
                </tr>
                 <tr>
                    <td>Votre prénom:</td>
                    <td><input type="text" name="prenom" value="" id="prenom"></td>
                </tr>
                 <tr>
                    <td>Votre age:</td>
                    <td><input type="text" name="age" value="" id="age"></td>
                </tr>
                 <tr>
                    <td>Votre numéro de t&eacute;l&eacute;phone:</td>
                    <td><input type="tel" name="tel" value="" id="tel" required="required"></td>
                </tr>
                 <tr>
                    <td>Votre adresse mail:</td>
                    <td><input type="email" name="email" value="" id="email" required="required"></td>
                </tr>
            </table>
        </fieldset>
        <fieldset>
            <legend>Votre candidature :</legend>
            <table>
                <tr>
                    <td>
                        <label for="question1">Êtes-vous mobile (déménagement) ? Si oui sur quelles régions ou départements ? </label>
                        <br /><textarea name="question1" id="question1" rows="2" cols="80"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="question2">Quelle est, selon vous, l&rsquo;entreprise id&eacute;ale ? </label>
                        <br /><textarea name="question2" id="question2" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="question3">Quel est, selon vous, le poste id&eacute;al ? </label><br />
                        <textarea name="question3" id="question3" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                        <label for="question4">Pourquoi le projet de rejoindre SMC vous int&eacute;resse-t-il ?</label>
                        <br /><textarea name="question4" id="question4" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                        <label for="question5">Qu&rsquo;est-ce qui vous motive sur la fonction de Technico-Commercial ?</label><br />
                        <textarea name="question5" id="question5" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                        <label for="question6">Avez-vous des doutes ou des interrogations sur le fait de rejoindre SMC en qualit&eacute; de Technico-Commercial ?</label>
                        <br /><textarea name="question6" id="question6" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                       <label for="question7">Quelles sont vos activit&eacute;s extraprofessionnelles et pourquoi vous plaisent-elles ?</label><br />
                       <textarea name="question7" id="question7" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                        <label for="question8">Quelle est votre plus grande r&eacute;ussite personnelle ou professionnelle ?</label>
                        <br /><textarea name="question8" id="question8" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                        <label for="question9">Quelle est votre plus grande r&eacute;ussite personnelle ou professionnelle ?</label>
                        <br /><textarea name="question9" id="question9" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                        <label for="question10">Si nous devions appeler vos amis, comment vous d&eacute;criraient-ils ?</label>
                        <br /><textarea name="question10" id="question10" rows="4" cols="80"></textarea>
                    </td>
                </tr>
                 <tr>
                    <td>
                       <label for="question11">Avez-vous d&rsquo;autres remarques ou des sujets sur lesquels vous souhaiteriez vous exprimer ?</label><br />
                       <textarea name="question11" id="question11" rows="4" cols="80"></textarea><br /> 
                    </td>
                </tr>
            </table>
        </fieldset>
        <div align=right><input type="submit" value="Envoyer" /></div>
    </form>
</div>
