<div id="avenant" class="contenu">

    <div id="entete">
        <img  src="/images/logo_smc_bleu3.jpg" alt="" />
        <p>SMC Pneumatique S.A. <br>
            Parc Gustave Eiffel <br>
            1, Bd de Strasbourg<br>
            CS 90297 BUSSY SAINT GEORGES<br>
            77607 MARNE LA VALLEE CEDEX<br>
            Tel : +33(0)1 64 76 10 00
            Fax : +33(0)1 64 76 10 10
            www.smc-france.fr
        </p>
    </div>
    <div>
        <div>
            <p style="text-align: center"><h3>Avenant à la Convention Annuelle</h3></p>
        </div>
        <div>
            <p>Objet: Accord de prix spécifique <br><br>
                entre SMC Pneumatique SA et la société : <?php echo $this->info_distrib['nom_distributeur']; ?><br>
                Cher partenaire,<br><br>
                Suite à votre demande, nous avons le plaisir de vous confirmer notre accord pour modifier<br><br>
                nos prix de vente selon les conditions particulières mentionnées ci-dessous.<br><br>
                Cet accord de prix spécifique étant exclusivement applicable pour le client : <?php echo $this->client_distrib['nom_client'] ?><br><br>
            En vue de l’obtention du marché:……. et/ou pour une durée de : ………………….<br>
            </p>
            <div id="avenantproduit">
                <table  class="enum">
                <tr>
                    <td>Référence produit</td>
                    <td>Ancien prix de vente</td>
                    <td>Nouveau prix de vente</td>
                </tr>
                <?php  foreach($this->article_info as $value){?>
                <tr>
                    <td><?php echo $value['reference_article'];?></td>
                    <td><?php echo $value['prix_achat_actuel'];?></td>
                    <td><?php echo $value['prix_accorde_demande_article']; ?></td>
                </tr><?php } ?>
            </table>
            </div> 
           
        </div>
    </div>
</div>