<?php 
ob_get_clean();
ob_start();
?>
<page backtop="20mm" backleft="15mm" backright="15mm" backbottom="120mm">
    <table>
        <tr>
            <td>Objet: Accord de prix spécifique entre SMC Pneumatique SA et la société : <?php echo $this->info_distrib['nom_distributeur']; ?></td>
        </tr>
        <tr>
            <td>
                 Cher partenaire,
            </td>
        </tr>
        <tr>
            <td>
                Suite à votre demande, nous avons le plaisir de vous confirmer notre accord pour modifier
                nos prix de vente selon les conditions particulières mentionnées ci-dessous.
                Cet accord de prix spécifique étant exclusivement applicable pour le client : <?php echo $this->client_distrib['nom_client'] ?>
                En vue de l’obtention du marché:……. et/ou pour une durée de : ………………….
            </td>
        </tr>
    </table>
    <table style='border: 1px solid black; border-collapse: collapse; width:100%;'>
        <tr  style='border: 1px solid black; line-height: 2;'>
            <td style='border: 1px solid black; width: 200px; text-align: center;'>Référence produit</td>
            <td style='border: 1px solid black; width: 150px; text-align: center;'>Ancien prix de vente</td>
            <td style='border: 1px solid black;width: 150px; text-align: center;'>Nouveau prix de vente</td>
        </tr>
        <?php  foreach($this->article_info as $value){?>
        <tr style='border: 1px solid black;'>
            <td style='border: 1px solid black; text-align: center;'><?php echo $value['reference_article'];?></td>
            <td style='border: 1px solid black; text-align: center;'><?php echo $value['prix_achat_actuel']?></td>
            <td style='border: 1px solid black; text-align: center;'><?php echo $value['prix_accorde_demande_article']?></td>
        </tr><?php } ?>
    </table>
    <table>
        
        <tr>
            <td>Fait à Bussy-Saint-Georges, en 2 exemplaires</td>
        </tr>
        <tr>
            <td>Le:</td>
        </tr>
    </table>
</page>
<?php $plopinette= ob_get_clean();
require('html2pdf/html2pdf.class.php');
try{$html2pdf->setDefaultFont('Arial');
    $pdf=new HTML2PDF('P','A4','fr');
    $pdf->pdf->SetDisplayMode('fullpage');
    
    $pdf->writeHTML($plopinette);
    
    $pdf->Output(APPLICATION_PATH. "/../docs/avenant_{$this->numwp}.pdf", 'F');
} catch(HTML2PDF_exception $e) {
die($e);
}
header("Location:/xdistrib/avenant2/numwp/{$this->numwp}");
