<div id="avenant" class="contenu">

    <div id="entete">
        <img  src="/images/logo_smc_bleu3.jpg" alt="" />
        <p>SMC Pneumatique S.A. <br>
            Parc Gustave Eiffel <br>
            1, Bd de Strasbourg<br>
            CS 90297 BUSSY SAINT GEORGES<br>
            77607 MARNE LA VALLEE CEDEX<br>
            Tel : +33(0)1 64 76 10 00
            Fax : +33(0)1 64 76 10 10
            www.smc-france.fr
        </p>
    </div>
    <div>
        <div>
            <p style="alignment-adjust: central"><h4>Avenant à la Convention Annuelle</h4></p>
        </div>
        <div>
            <p>Objet: Accord de prix spécifique <br>
            entre SMC Pneumatique SA et la société : <?php echo $this->info_distrib['nom_distributeur']; ?>
            Cher partenaire,<br>
            Suite à votre demande, nous avons le plaisir de vous confirmer notre accord pour modifier <br>
            nos prix de vente selon les conditions particulières mentionnées ci-dessous.
            Cet accord de prix spécifique étant exclusivement applicable pour le client : <?php echo $this->client_distrib['nom_client'] ?>
            En vue de l’obtention du marché:……. et/ou pour une durée de : …………………..
            </p>
        </div>
    </div>
</div>