<?php
$this->title = 'Xdistrib/visualisation';
$this->headTitle($this->title);
?>
<?php
$this->title = 'Xdistrib/création';
$this->headTitle($this->title);
?>
<div id="plop3" class="contenu">
    <h2>Création d'une offre Xprice-distrib</h2>
    <div id="workplace" class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table class="table_info">
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->infos_offres->OBORNO; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo  $this->datefinal; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div class="clear"></div>
    <div id="information2" class="workplace2">
            <fieldset id="info_user" class="field_info_2">
                <legend>Informations<br>Commercial</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Prénom:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Téléphone:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Holon:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>User workplace:</td>
                        <td></td>
                    </tr>
                </table>
            </fieldset>
            <fieldset id="info_distributeur" class="field_info_2" >
                <legend>Informations<br>Distributeur</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td><?php echo trim($this->infos_distrib['OKCUNM']);?></td>
                    </tr>
                    <tr>
                        <td>Prénom Nom du contact:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>code postal/Ville:</td>
                        <td><?php echo $this->infos_distrib['OKCUA4'];?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->infos_distrib['OKCUNO'];?></td>
                    </tr>
                </table>
            </fieldset>             
            
            <fieldset id="info_client" class="field_info_2"> 
                <legend>Informations<br>Client Final</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td colspan="2"><?php echo trim($this->infos_client['OKCUNM'])?></td>
                    </tr>
                    <tr>
                        <td>Code Postal/ville</td>
                        <td><?php echo $this->infos_client['OKCUA4']?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->infos_client['OKCUNO']?></td>
                    </tr>
                     <tr>
                        <td>Projet:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Client cible PAC :</td>
                        <td>
                            <span class="pac"><input type="radio" name="pac" value="oui">Oui</span>
                            <span class="pac"><input type="radio" name="pac" value="non">Non</span>
                        </td>
                    </tr>
                </table>
           </fieldset>
        </div>
        <div class="clear"></div>
</div>