<?php
$this->title = 'Xdistrib/visualisation';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/Xdistrib/calculRemiseDistrib.js');
?>
<?php
$this->title = 'Xdistrib/création';
$this->headTitle($this->title);
?>
<div id="plop3" class="contenu">
    <h2>Création d'une offre Xprice-distrib</h2>
    <form method="post" >
        <div id="workplace" class="workplace">
            <fieldset id="wp" class="field">
                <legend>Informations offre</legend>
                <table class="table_info">
                    <tr>
                        <td>Numéro workplace de l'offre :</td>
                        <td><?php echo $this->infos_offres->OBORNO; ?></td>
                    </tr>
                    <tr>
                        <td>Date de l'offre workplace :</td>
                        <td><?php echo  $this->datefinal; ?></td>
                    </tr>
                </table>
            </fieldset>
        </div>
        <div class="clear"></div>
        <div id="information2" class="workplace2">
            <fieldset id="info_user" class="field_info_2">
                <legend>Informations<br>Commercial</legend>
                <table>
                    <tr>
                        <td>Nom du TC SMC:</td>
                        <td><?php echo $this->infos_tc['nom_user']?></td>
                    </tr>
                    <tr>
                        <td>Prénom du TC SMC:</td>
                        <td><?php echo $this->infos_tc['prenom_user']?></td>
                    </tr>
                    <tr>
                        <td>Email du TC SMC:</td>
                        <td><?php echo $this->infos_tc['email_user']?></td>
                    </tr>
                    <tr>
                        <td>Nom du DD SMC:</td>
                        <td><?php echo $this->infos_dd->nom_user; ?></td>
                    </tr>
                    <tr>
                        <td>Prénom du DD SMC :</td>
                        <td><?php echo $this->infos_dd->prenom_user; ?></td>
                    </tr>
                    <tr>
                        <td>Email du DD SMC:</td>
                        <td><?php echo $this->infos_dd->email_user; ?></td>
                    </tr>
                </table>
            </fieldset>
            <fieldset id="info_distributeur" class="field_info_2" >
                <legend>Informations<br>Distributeur</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td><?php echo trim($this->infos_distrib['OKCUNM']);?></td>
                    </tr>
                    <tr>
                        <td>Prénom Nom du contact:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>code postal/Ville:</td>
                        <td><?php echo $this->infos_distrib['OKCUA4'];?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->infos_distrib['OKCUNO'];?></td>
                    </tr>
                </table>
            </fieldset>             

            <fieldset id="info_client" class="field_info_2"> 
                <legend>Informations<br>Client Final</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td colspan="2"><?php echo trim($this->infos_client['OKCUNM'])?></td>
                    </tr>
                    <tr>
                        <td>Code Postal/ville</td>
                        <td><?php echo $this->infos_client['OKCUA4']?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->infos_client['OKCUNO']?></td>
                    </tr>
                     <tr>
                        <td>Projet:</td>
                        <td><?php echo $this->info_industry['nom_industry'] ;?></td>
                    </tr>
                </table>
           </fieldset>
        </div>
            <div class="clear"></div>
        <div id="demandeArticle" class="workplace">
            <fieldset class="field">
                <legend>Produits</legend>
                <table  id="article" class="enum">
                    <tr>
                        <td>Références produits</td>
                        <td>Quantité</td>
                        <td>Prix Tarif</td>
                        <td>Remise Contractuelle</td>
                        <td>Prix Achat demandé DISTRIBUTEUR</td>
                        <td>Prix Conseillé Client</td>
                        <td>Remise Demandée</td>
                        <td>Remise référence ou série</td>
                    </tr>
                    <?php foreach($this->affiche_offre as $k=>$value){ ?>
                    <tr>
                        <td><?php echo trim($value['OBITDS']); ?></td><input type="hidden" name="reference[]" value="<?php echo trim($value['OBITDS']); ?>" >
                        <td><?php echo round($value['OBORQT'],2); ?></td><input type="hidden" name="quantite[]" value="<?php echo round($value['OBORQT'],2); ?>" >
                        <td id="pwp-<?php echo $k?>"><?php echo round($value['OBSAPR'],2)?></td><input type="hidden" name="prix_tarif_dis[]" value="<?php echo round($value['OBSAPR'],2); ?>" >
                        <td><?php echo round($value['OBVTCD'],2); ?><input  type="hidden" name="remiseA[]" id="rad-<?php echo $k ;?>" value="<?php echo $value['OBVTCD'] ;?>"></td>
                        <td><?php echo round($value['OBNEPR'],2); ?></td><input type="hidden" name="prix_demande[]" value="<?php echo round($value['OBNEPR'],2);?>">
                        <td><input style="background-color: #74aaca;height:30px; width:80px;margin-left:10px;" type="text" name="prix_achat_client_final[]" id="Prix_achat_client_final" ></td>
                        <td><?php  $remiseB =(100-((100* $value['OBNEPR'])/$value['OBSAPR']));?><input type="text" name="remiseB[]" value="<?php echo round($remiseB,2).'%';?>"</td>
                        <td><input required="required" style="background-color: #74aaca;height:30px; width:80px;margin-left:10px;" type="text" name="serie[]" value=""></td>
                    </tr> <?php }?>
                </table>
            </fieldset>
        </div>
        <div class="clear"></div>
        <div id="concurrent" class="workplace">
            <fieldset  class="field">
                <legend>Concurrence</legend>
                <table  id="concurrents" class="enum">
                    <?php $i=count($this->affiche_offre);?>
                    <tr>
                        <td>Concurrents</td>
                        <td>Références Produits</td>
                        <td>Prix Tarif CONCURRENT</td>
                        <td>Prix spécial accordé CONCURRENT</td>
                    </tr>
                    <tr>
                        <td><input type="text" name="nom_concurrent"></td>
                        <td><input type="text" name="reference_produit"></td>
                        <td><input type="text" name="prix_tarif"></td>
                        <td><input type="text" name="prix_spe"></td>
                    </tr> 
                </table>
            </fieldset>
        </div>
        <div class="clear"></div>
        <div id="contexte_service" class="workplace">
            <fieldset class="field">
                <legend>Contexte de la demande</legend>
                 <textarea name="contexte" cols="120" rows="7"><?php echo $this->context_info;?></textarea>
            </fieldset>
       
            <fieldset class="field">
                <legend>Services Associés apportés par le distributeur</legend>
                <table>
                    <tr>
                        <td><input type="checkbox" name="produitdedie" value="Stock produit dédié">Stock produit dédié</td>
                        <td><input type="checkbox" name="ecatalogue" value="E-catalogue">E-catalogue</td>
                        <td><input type="checkbox" name="journeetech" value="Journée technique sur site client">Journée technique sur site client</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" name="accescom" value="Accès commercial sur site">Accès commercial sur site</td>
                        <td><input type="checkbox" name="identconc" value="Identification concurrence">Identification concurrence</td>
                        <td><input type="checkbox" name="interlocuteur" value="Interlocuteurs connus">Interlocuteurs connus(préconisateurs, décisionnaires)</td>
                    </tr>
                </table>
                <fieldset>
                    <legend>Autres</legend>
                    <p>ex : nb de visites prévues sur le site, référencement des produits SMC dans la base du clients…</p>
                    <textarea name="service_associe" cols="120" rows="7"></textarea>
                </fieldset>
            </fieldset>
        </div>        
        <div class="clear"></div>
         <input class="submit" type="submit" value="envoyer la demande">
    </form>
</div>