<?php
$this->title = 'Xdistrib/création';
$this->headTitle($this->title);
?>
<div id="plop3" class="contenu">
    <h2>Création d'une offre Xprice-distrib</h2>
    <div id="workplace" class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table class="table_info">
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->infos_offres->OBORNO; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo  $this->datefinal; ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->trackingNumber; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <form action ="" method ="post">
        <div id="information2" class="workplace2">
            <fieldset id="info_user" class="field_info_2">
                <legend>Informations Commercial</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td><?php echo $this->user_info['nom_user'];?></td>
                    </tr>
                    <tr>
                        <td>Prénom:</td>
                        <td><?php echo $this->user_info['prenom_user'];?></td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td><?php echo $this->user_info['email_user'];?></td>
                    </tr>
                    <tr>
                        <td>Téléphone:</td>
                        <td><?php echo $this->user_info['tel_user'];?></td>
                    </tr>
                    <tr>
                        <td>Holon:</td>
                        <td><?php echo $this->user_info['nom_holon']; ?></td>
                    </tr>
                    <tr>
                        <td>User workplace:</td>
                        <td><?php echo $this->user_info['numwp_user'];?></td>
                    </tr>
                </table>
            </fieldset>
            <fieldset id="info_distributeur" class="field_info_2" >
                <legend>Informations Distributeur</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td><?php echo $this->distrib_info['distrib'];?></td>
                    </tr>
                    <tr>
                        <td>Prénom Nom du contact:</td>
                        <td><?php echo $this->distrib_info['nom_contact_distrib'];?></td>
                    </tr>
                    <tr>
                        <td>Ville:</td>
                        <td><?php echo $this->distrib_info['ville_distrib'];?></td>
                    </tr>
                    <tr>
                        <td>Code Postal:</td>
                        <td><?php echo $this->distrib_info['codepostal_distrib'];?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->distrib_info['numwp_distrib'];?></td>
                    </tr>
                </table>
            </fieldset>             
            
            <fieldset id="info_client" class="field_info_2"> 
                <legend>Informations Client Final</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td><?php echo $this->client_info['nom_client_final']?></td>
                    </tr>
                    <tr>
                        <td>Code Postal:</td>
                        <td><?php echo $this->client_info['codepostal_client']?></td>
                    </tr>
                    <tr>
                        <td>Ville:</td>
                        <td><?php echo $this->client_info['ville_client']?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->client_info['numwp_client']?></td>
                    </tr>
                    <tr>
                        <td>Potentiel:</td>
                        <td><?php echo $this->client_info['potentiel']?></td>
                    </tr>
                     <tr>
                        <td>Projet:</td>
                        <td></td>
                    </tr>
                </table>
           </fieldset>
        </div>
    </form>
</div>