<?php
$this->title = 'Xdistrib/visualisation';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/Xdistrib/calculRemiseDistrib.js');
?>
<?php
$this->title = 'Xdistrib/création';
$this->headTitle($this->title);
?>
<div id="plop3" class="contenu">
    <h2>Création d'une offre Xprice-distrib</h2>
    <form>
        <div id="workplace" class="workplace">
            <fieldset id="wp" class="field">
                <legend>Informations offre</legend>
                <table class="table_info">
                    <tr>
                        <td>Numéro workplace de l'offre :</td>
                        <td><?php echo $this->infos_offres->OBORNO; ?></td>
                    </tr>
                    <tr>
                        <td>Date de l'offre workplace :</td>
                        <td><?php echo  $this->datefinal; ?></td>
                    </tr>
                </table>
            </fieldset>
        </div>
        <div class="clear"></div>
        <div id="information2" class="workplace2">
            <fieldset id="info_user" class="field_info_2">
                <legend>Informations<br>Commercial</legend>
                <table>
                    <tr>
                        <td>Nom du TC SMC:</td>
                        <td><?php echo $this->infos_tc['nom_user']?></td>
                    </tr>
                    <tr>
                        <td>Prénom du TC SMC:</td>
                        <td><?php echo $this->infos_tc['prenom_user']?></td>
                    </tr>
                    <tr>
                        <td>Email du TC SMC:</td>
                        <td><?php echo $this->infos_tc['email_user']?></td>
                    </tr>
                    <tr>
                        <td>Nom du DD SMC:</td>
                        <td><?php echo $this->infos_dd->nom_user; ?></td>
                    </tr>
                    <tr>
                        <td>Prénom du DD SMC :</td>
                        <td><?php echo $this->infos_dd->prenom_user; ?></td>
                    </tr>
                    <tr>
                        <td>Email du DD SMC:</td>
                        <td><?php echo $this->infos_dd->email_user; ?></td>
                    </tr>
                </table>
            </fieldset>
            <fieldset id="info_distributeur" class="field_info_2" >
                <legend>Informations<br>Distributeur</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td><?php echo trim($this->infos_distrib['OKCUNM']);?></td>
                    </tr>
                    <tr>
                        <td>Prénom Nom du contact:</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>code postal/Ville:</td>
                        <td><?php echo $this->infos_distrib['OKCUA4'];?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->infos_distrib['OKCUNO'];?></td>
                    </tr>
                </table>
            </fieldset>             

            <fieldset id="info_client" class="field_info_2"> 
                <legend>Informations<br>Client Final</legend>
                <table>
                    <tr>
                        <td>Nom:</td>
                        <td colspan="2"><?php echo trim($this->infos_client['OKCUNM'])?></td>
                    </tr>
                    <tr>
                        <td>Code Postal/ville</td>
                        <td><?php echo $this->infos_client['OKCUA4']?></td>
                    </tr>
                    <tr>
                        <td>User Workplace:</td>
                        <td><?php echo $this->infos_client['OKCUNO']?></td>
                    </tr>
                     <tr>
                        <td>Projet:</td>
                        <td><?php echo $this->info_industry['nom_industry'] ;?></td>
                    </tr>
                    <tr>
                        <td>Client cible PAC :</td>
                        <td>
                            <span class="pac"><input type="radio" name="pac" value="oui">Oui</span>
                            <span class="pac"><input type="radio" name="pac" value="non">Non</span>
                        </td>
                    </tr>
                </table>
           </fieldset>
        </div>
            <div class="clear"></div>
        <div id="demandeArticle" class="workplace">
            <fieldset class="field">
                <legend>Produits</legend>
                <table  id="article" class="enum">
                    <tr>
                        <td>Références produits</td>
                        <td>Quantité</td>
                        <td>Prix Tarif</td>
                        <td>Remise Contractuelle</td>
                        <td>Prix Achat actuel DISTRIBUTEUR</td>
                        <td>Prix Achat demandé DISTRIBUTEUR</td>
                        <td>Prix Achat CLIENT FINAL</td>
                        <td>Remise supplémentaire DISTRIBUTEUR</td>
                        <td>Remise référence ou série</td>
                    </tr>
                    <?php foreach($this->affiche_offre as $k=>$value){ ?>
                    <tr>
                        <td><?php echo $value['OBITDS']; ?></td>
                        <td><?php echo round($value['OBORQT'],2); ?></td>
                        <td id="pwp-<?php echo $k?>"><?php echo round($value['OBSAPR'],2)?></td>
                        <td><input style="background-color: #74aaca;height:30px; width:80px;margin-left:10px;" class="rad" name="remiseA[]" id="rad-<?php echo $k ;?>" value=""></td>
                        <td><input style="background-color: #74aaca;height:30px; width:80px;margin-left:10px;" class="pad" name="prixAchatActuel[]" id="pad-<?php echo $k ;?>" value=""></td>
                        <td><?php echo round($value['OBNEPR'],2); ?></td>
                        <td><input style="background-color: #74aaca;height:30px; width:80px;margin-left:10px;" type="text" name="prix_achat_client_final[]" id="Prix_achat_client_final" ></td>
                        <td><?php  $remiseB =(100-((100* $value['OBNEPR'])/$value['OBSAPR']));?><input type="text" name="remiseB[]" value="<?php echo round($remiseB,2).'%';?>"</td>
                        <td>
                            <span><input type="radio" name="serie" value="référence">Remise référence</span>
                            <span><input type="radio" name="serie" value="série">Remise série</span>
                        </td>
                    </tr> <?php }?>
                </table>
            </fieldset>
        </div>
        <div class="clear"></div>
        <div id="contexte_service" class="workplace">
            <fieldset class="field">
                <legend>Contexte de la demande</legend>
                 <textarea name="contexte" cols="120" rows="7"></textarea>
            </fieldset>
            <fieldset class="field">
                <legend>Services Associés apportés par le distributeur</legend>
                 <textarea name="service" cols="120" rows="7"></textarea>
            </fieldset>
        </div>    
        <div class="clear"></div>
         <input class="submit" type="submit" value="envoyer la demande">
    </form>
</div>