<?php
$this->title = 'Xdistrib/accueil';
$this->headTitle($this->title);
?>
<div class="contenu">
    <h2>Xdistrib</h2>
    <h3>Demande en ligne pour Prix Spéciaux Distributeurs </h3> 
    <table class="enum">
        <tr>
             <?php if($this->fonction == 3 || $this->fonction == 5 || $this->fonction == 13 || $this->fonction ==10 || $this->fonction ==29 || $this->fonction==23 || $this->fonction==32 || $this->fonction == 6  || $this->fonction == 40 || $this->fonction == 45){?>
            <th>Commercial</th>
        <?php } ?>
            <th>Numéro Workplace</th>
            <th>Tracking number</th>
             <th>Distributeur</th>
            <th>Nom Client</th>
            <th>Date demande</th>
             <th>état validation</th>
        </tr>
    <?php  foreach($this->recapitulatif as $tagada){ foreach ($tagada as $key=>$result){
        ?><tr>
            <?php if( $this->fonction == 3 || $this->fonction == 5 || $this->fonction == 13 || $this->fonction == 10 || $this->fonction ==29 || $this->fonction==23 || $this->fonction==32 || $this->fonction == 6 || $this->fonction == 40 || $this->fonction == 45){?>
             <td><?php echo $result['nom_user'];?></td>
        <?php } ?>
            <td><?php echo $result['num_workplace_demande_xdistrib']; ?></td>
            <td><?php echo $result['tracking_number_demande_xdistrib']; ?></td>
            <td><?php echo $result['nom_distributeur']; ?></td>
            <td><?php echo $result['nom_client']; ?></td>
             <td><?php echo $result['date_demande_xdistrib']; ?></td>
        <?php if($result['etat_validation']=="validee" || $result['etat_validation']=="validée" || $result['etat_validation']=="creation"){ ?>
             <td>en cours <br> <?php if($result['nom_validation']=="creation"){echo 'cdr';}
                                    elseif ($result['nom_validation']=="cdr") {echo 'fobfr';}
                                     elseif ($result['nom_validation']=="fobfr") {echo 'supply';}
                                     elseif ($result['nom_validation']=="supply") {echo 'dbd';}
                                     elseif ($result['nom_validation']=="dbd") {echo 'dirco';}
                                   ?></td><?php }elseif($result['etat_validation']=="enAttente"){
                                       if($result['nom_validation']=="reponse"){
                                       ?><td> en cours DBD</td> <?php }elseif($result['nom_validation']=="dbd"){
                                           ?><td> en attente ITC</td><?php 
                                       }
                                   }
                                    else{ ?>
             <td><?php echo $result['etat_validation'];?><br></td>
    <?php }   ?>
             <td><a href="<?php echo $this->url(array("controller"=>"xdistrib","action"=>"consult","numwp"=>$result['num_workplace_demande_xdistrib']));?>" <button class="retour" id="historique-<?php echo $k; ?>">historique</button></a>
             </td>
              <?php if($this->fonction == 5 || $this->fonction ==29 ){?>
             <td><a href="<?php echo $this->url(array("controller"=>"xdistrib","action"=>"validatedbd","numwp"=>$result['num_workplace_demande_xdistrib']));?>" <button class="retour" id="validate-<?php echo $k; ?>">Valider</button></a></td>
        <?php } elseif($this->fonction == 13){?>
             <td><a href="<?php echo $this->url(array("controller"=>"xdistrib","action"=>"validatedirco","numwp"=>$result['num_workplace_demande_xdistrib']));?>" <button class="retour" id="validate-<?php echo $k; ?>">Valider</button></a></td>
        <?php } elseif( $this->fonction == 10 || $this->fonction == 45 ){?>
             <td><a href="<?php echo $this->url(array("controller"=>"xdistrib","action"=>"validatedrv","numwp"=>$result['num_workplace_demande_xdistrib']));?>" <button class="retour" id="validate-<?php echo $k; ?>">Valider</button></a></td>
        <?php } elseif($this->fonction == 32){?>
             <td><a href="<?php echo $this->url(array("controller"=>"xdistrib","action"=>"validatesupply","numwp"=>$result['num_workplace_demande_xdistrib']));?>" <button class="retour" id="validate-<?php echo $k; ?>">Valider</button></a></td>
         <?php }elseif($this->fonction == 23){?>
             <td><a href="<?php echo $this->url(array("controller"=>"xdistrib","action"=>"validatefobfr","numwp"=>$result['num_workplace_demande_xdistrib']));?>" <button class="retour" id="validate-<?php echo $k; ?>">Valider</button></a></td>
        <?php } ?>
</tr>
    <?php } }?>
    </table>
    <?php if($this->fonction == 45){
          foreach ($this->recapitulatif as $tagada){
          echo $tagada;}
          } ?>
</div>