<?php
$this->title = 'Xdistrib/recherche';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/multipleselect.js');
?>
<div class="contenu">
    <h2>Xdistrib</h2>
    <h3>Recherche Xdistrib par client </h3> 
    <form method="post" action="recherche2">
        <div class="workplace">
            <table>
                <tr>
                    <td>Nom client :</td>
                    <td>
                        <select name="liste_distributeur" id="nom_distributeur">
                            <option>Choississez le nom du distributeur</option>
                            <?php foreach($this->result1 as $value1)
                            {?>
                            <option value="<?php echo $value1['numwp_distributeur']; ?>"><?php echo $value1['nom_distributeur']; ?></option>
                            <?php }?>
                        </select>
                    </td>
                </tr>    
            </table>
            <p><input type="submit" name="valider" value="valider"></p>
        </div>
    </form>
</div>