<?php
$this->title = 'Xdistrib/recherchecomptable';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/multipleselect.js');
?>
<div class="contenu">
    <h2>Xdistrib</h2>
    <h3>Recherche Xdistrib par Distributeur </h3> 
    <form method="post" action="recherchecomptable2">
        <div class="workplace">
            <table>
                <tr>
                    <td>Nom client :</td>
                    <td>
                        <select name="liste_distributeur" id="nom_distributeur">
                            <option>Choississez le nom du distributeur</option>
                            <?php foreach($this->code_client as $value1)
                            {?>
                            <option value="<?php echo $value1['numwp_distributeur']; ?>"><?php echo $value1['nom_distributeur']; ?></option>
                            <?php }?>
                        </select>
                    </td>
                    <td>Choississez le code article :</td>
                    <td>
                        <select name="liste_code_article" id="code_article">
                            <option value="0">choississez un code article</option>
                            <?php foreach($this->code_article as $value2)
                            {?>
                            <option value="<?php echo $value2['code_article']; ?>"><?php echo $value2['code_article']; ?></option>
                            <?php }?>c
                        </select>
                    </td>
                </tr>    
            </table>
            <p><input type="submit" name="valider" value="valider"></p>
        </div>
    </form>
</div>