<?php
$this->title = 'Xdistrib/accueil';
$this->headTitle($this->title);
$this->headScript()->appendFile('/js/controllers/xprice/recalculeprix_marge.js');
$this->headScript()->appendFile('/js/numFormat.js');
$this->headScript()->appendFile('/js/controllers/xprice/afficher_masquer_validations.js');
?>
<div class="contenu">
    <h2>Validation de l'offre XDISTRIB par DBD</h2>
    <div id="workplace" class="workplace">
        <fieldset id="wp" class="field">
            <legend>Informations offre</legend>
            <table class="table_info">
                <tr>
                    <td>Numéro workplace de l'offre :</td>
                    <td><?php echo $this->numwp; ?></td>
                </tr>
                <tr>
                    <td>Date de l'offre workplace :</td>
                    <td><?php echo $this->dateplop; ?></td>
                </tr>
                <tr>
                    <td>Tracking number :</td>
                    <td><?php echo $this->info_demande_xdistrib['tracking_number_demande_xdistrib']; ?></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div class="clear"></div>
    <div id="information2" class="workplace2">
        <fieldset id="info_user" class="field_info_2">
            <legend>Informations<br>Commercial</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->user_info['nom_user'];?></td>
                </tr>
                <tr>
                    <td>Prénom:</td>
                    <td><?php echo $this->user_info['prenom_user'];?></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><?php echo $this->user_info['email_user'];?></td>
                </tr>
                <tr>
                    <td>Téléphone:</td>
                    <td><?php echo $this->user_info['tel_user'];?></td>
                </tr>
                <tr>
                    <td>Holon:</td>
                    <td><?php echo $this->nom_holon['nom_holon']; ?></td>
                </tr>
                <tr>
                    <td>User workplace:</td>
                    <td><?php echo $this->user_info['numwp_user'];?></td>
                </tr>
            </table>
        </fieldset>
        <fieldset id="info_distributeur" class="field_info_2" >
            <legend>Informations<br>Distributeur</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td><?php echo $this->distrib_info['nom_distributeur'];?></td>
                </tr>
                <tr>
                    <td>Prénom Nom du contact:</td>
                    <td><?php echo $this->distrib_info['contact_distributeur'];?></td>
                </tr>
                <tr>
                    <td>Ville:</td>
                    <td><?php echo $this->distrib_info['agence_distributeur'];?></td>
                </tr>
                <tr>
                    <td>Code Postal:</td>
                    <td><?php echo $this->distrib_info['code_postal_distributeur'];?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->distrib_info['numwp_distributeur'];?></td>
                </tr>
            </table>
        </fieldset>             

        <fieldset id="info_client" class="field_info_2"> 
            <legend>Informations<br>Client Final</legend>
            <table>
                <tr>
                    <td>Nom:</td>
                    <td colspan="2"><?php echo $this->client_info['nom_client']?></td>
                </tr>
                <tr>
                    <td>Code Postal:</td>
                    <td><?php echo $this->client_info['codepostal_client']?></td>
                </tr>
                <tr>
                    <td>Ville:</td>
                    <td><?php echo $this->client_info['ville_client']?></td>
                </tr>
                <tr>
                    <td>User Workplace:</td>
                    <td><?php echo $this->client_info['numwp_client']?></td>
                </tr>
                 <tr>
                    <td>Projet:</td>
                    <td><?php echo $this->client_info['nom_industry']?></td>
                </tr>
            </table>
       </fieldset>
    </div>
    <div class="clear"></div>
    <div id="concurrent" class="workplace">
        <fieldset  class="field">
            <legend>Concurrence</legend>
            <table  id="concurrents" class="enum">
                <tr>
                    <td>Concurrents</td>
                    <td>Références Produits</td>
                    <td>Prix Tarif CONCURRENT</td>
                    <td>Prix spécial accordé CONCURRENT</td>
                </tr>
                <?php foreach($this->concurrent_info as $val){ ?>
                <tr>
                    <td><?php echo $val['nom_concurrent']; ?></td>
                    <td><?php echo $val['reference_article']; ?></td>
                    <td><?php echo $val['prix_concurrent']; ?></td>
                    <td><?php echo $val['prix_special_concurrent']; ?></td>
                </tr> <?php } ?>
            </table>
        </fieldset>
    </div>
    <div class="clear"></div>
     <div id="contexte_service" class="workplace">
        <fieldset class="field">
            <legend>Contexte de la demande</legend>
            <?php  foreach($this->contexte_info as $contexte){?>
            <p><?php echo $contexte;?></p><?php } ?>
            <table class='enum'>

                <tr><?php foreach($this->service_info as $key=>$value) { if($value != null && $key != "id_service_distrib" && $key != "numwp" ){?>
                <td><?php echo $value;} ?></td> <?php } ?>
                </tr>
            </table>
        </fieldset>
     </div>
     <div class="clear"></div>
     <div id="commentaire" class="workplace">
        <fieldset class="field">
            <legend>Commentaires</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) { ?>
                    <tr>
                        <td>Commentaire <?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['commentaire']); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </fieldset>
    </div>
     <div class="clear"></div>
     <form method="post">
        <div id="demandeArticle" class="workplace">
            <fieldset class="field">
                <legend>Produits</legend>
                <table  id="article" class="enum">
                    <tr>
                        <td>Code Article</td>
                        <td>Références produits</td>
                        <td>Quantité</td>
                        <td>Prix Achat actuel DISTRIBUTEUR</td>
                        <td>Prix Achat demandé DISTRIBUTEUR</td>
                        <td>Prix Conseillé CLIENT FINAL</td>
                        <td>Remise référence ou série</td>
                        <td>Prif fob</td>
                        <td>Prix cif</td>
                        <td>prix accordé</td>
                        <td>remise accordée</td>
                        <td>marge</td>
                    </tr>
                    <?php foreach($this->article_info as $k=>$value){ ?>
                    <tr>
                        <td><input readonly="readonly" value="<?php echo $value['code_article'] ?>"  name="<?php echo 'code_article[]'; ?>"></td>
                        <td style="width: 70px;"><?php echo $value['reference_article']; ?></td>
                        <td id="qt-<?php echo $k; ?>"><?php echo $value['quantite_demande_article']; ?></td>
                        <td id="pwp-<?php echo $k; ?>"><?php echo $value['prix_achat_actuel']; ?></td>
                        <td id="pd-<?php echo $k; ?>"><?php echo $value['prix_demande_article']; ?></td>
                        <td><?php echo $value['prix_client_final']; ?></td>
                        <td><?php echo $value['serie']; ?></td>
                        <td><input readonly="readonly" class="fob" id="fob-<?php echo $k;?>" type="text" name="fob[]" value="<?php echo $value['prix_fob_demande_article']; ?>"></td><input class="totfob" type="hidden" id="totfob-<?php echo $k;?>" value ="<?php echo $value['quantite_demande_article']*$value['prix_fob_demande_article']; ?>">
                        <td id="cif-<?php echo $k; ?>"><?php echo $value['prix_cif_demande_article']; ?></td>
                         <td><input class="pda" id="pda-<?php echo $k; ?>" value="<?php echo $value['prix_demande_article']; ?>" name="<?php echo 'prix_accorde_article[]' ?>" style="background-color: #74aaca;"></td>
                        <td><input class="ra" id="ra-<?php echo $k; ?>" value="<?php $val=(($value['prix_demande_article']*100)/$value['prix_achat_actuel']) ;echo round($val,2). "%"; ?>" name="<?php echo 'remise_accorde_article[]' ?>" style="background-color: #74aaca;"></td>
                        <td><input class="ma" id="ma-<?php echo $k;?>" <?php $ma=100*(1-($value['prix_cif_demande_article']/$value['prix_demande_article']));?> value="<?php  echo round($ma,2)."%" ;?>" name="marge[]"></td>
                        <td><input type="hidden"  class="caa" id="caa-<?php echo $k;?>"  value="<?php echo round((($value['prix_demande_article'])*$value['quantite_demande_article']),2); ?>" name="caa" style="background-color:yellow;"></td>
                    </tr> <?php }?>
                    <tr>
                            <td colspan="3">total</td>
                            <td><input class="cab" id="cab-affiche"
                               <?php $cab=0;foreach($this->article_info as $result)
                                {$cab+=($result['quantite_demande_article']*$result['prix_achat_actuel']);
                            
                            } ?>value="<?php echo number_format($cab, 2, '.', ' '); ?>">
                                <input type="hidden" id="cab" class="calculHidden" value="<?php echo $cab; ?>">
                            </td>
                            <td><input class="cad" id="cad-affiche"
                               <?php $cad=0;foreach($this->article_info as $result)
                                {$cad+=($result['quantite_demande_article']*$result['prix_demande_article']);
                            
                            } ?>value="<?php echo number_format($cad, 2, '.', ' '); ?>">
                                <input type="hidden" id="cad" class="calculHidden" value="<?php echo $cad; ?>"></td>
                             <td><input class="caf" id="caf-affiche"
                               <?php $caf=0;foreach($this->article_info as $result)
                                {$caf+=($result['quantite_demande_article']*$result['prix_client_final']);
                            
                            } ?>value="<?php echo number_format($caf, 2, '.', ' '); ?>">
                                <input type="hidden" id="caf" class="calculHidden" value="<?php echo $caf; ?>"></td>
                             <td></td>
                            <td >
                                 <?php $Cfob=0; foreach($this->article_info as $result){
                                    $Cfob+=($result['quantite_demande_article']*$result['prix_fob_demande_article']);
                                }; echo number_format($Cfob, 2, '.', ' ');?>
                            </td>
                            <td >
                                 <input  id="ccif-affiche"<?php $Ccif=0; foreach($this->article_info as $result){
                                    $Ccif+=($result['quantite_demande_article']*$result['prix_cif_demande_article']);
                                }?> value="<?php echo number_format($Ccif, 2, '.', ' '); ?>">
                                <input id="ccif" type="hidden" class="calculHidden" value="<?php echo $Ccif; ?>">
                            </td>
                            <td >
                                 <input id="caat-affiche" <?php $CAa=0; foreach($this->article_info as $result){
                                    $CAa+=(($result['prix_demande_article'])*$result['quantite_demande_article']);
                                    }?>  value ="<?php echo number_format($CAa, 2, '.', ' '); ?>" >
                                <input id="caat" type="hidden" class="calculHidden" value="<?php echo $CAa; ?>" >
                            </td>
                            <td> <input id="mo"  <?php $mo=100*(1-($CAa/$cab));?> value="<?php echo round($mo,2)."%"; ?>"></td>
                            <td> <input name="mamo" id="mamo"<?php $mamo = 100*(1-($Ccif/$CAa))?> value ="<?php echo round($mamo,2)."%";?>"></td>
                            
                        </tr>
                </table>
            </fieldset>
        </div>
         <div class="clear"></div>
        <div id="validation" class="workplace">
        <button class="submit" id="historiqueVal" name="historiqueVal" value="historiqueVal">Historique validation</button>
        <fieldset  id='valid_hist' class='field'>
            <legend>Validation</legend>
            <table class="enum">
                <?php foreach (@$this->validations as $key => $value) {if($value['etat_validation']!="enAttente"){ ?>
                    <tr>
                        <td><?php echo strtolower($this->usersValidations[$key]['fonction']); ?></td>
                        <td><?php echo $value['date_validation']; ?></td>
                        <td><?php echo nl2br($value['etat_validation']); ?></td>
                    </tr>
                <?php } } ?>
                     <tr>
                        <td><?php echo $this->encoursFonction; ?></td>
                        <td></td>
                        <td><?php echo $this->encoursNom; ?></td>
                    </tr>
                <?php if ($this->fermeturevalide=="fermee") { ?>
                    <tr><td colspan = "3" style="text-align:center;">---------FIN DE LA PROCEDURE--------</td></tr>
                    <?php }else {?><tr><td colspan = "3" style="text-align:center;">--------PROCEDURE EN COURS--------</td></tr> <?php }?>
            </table>
        </fieldset>
    </div>
         <div id="dd" class="workplace">
             <fieldset class="field">
                <legend>Commentaire DBD</legend>
                <textarea name="commentaire_dbd" cols="75" rows="10"></textarea>
                <?php
                if (!is_null($this->commentId)) {
                    ?>
                    <input type="hidden" name="reponse" value="<?php echo $this->commentId; ?>">
                    <?php
                }
                ?>
            </fieldset>
        </div>
        <div id="valid_dd" class="workplace">
            <input type="radio" name="validation" value="nonValide"> La demande n'est pas validée <br>
            <input type="radio" name="validation" value="validee"> La demande est validée <br>
            <input type="radio" checked="checked" name="validation" value="enAttente">  en attente de réponse<br>
           <input hidden="hidden" name="nom_validation" value="validation_dbd">
            <input hidden="hidden" name="date_validation" value="<?php echo date("Y-m-d H:i:s") ?>">
            <input hidden="hidden" name="dbd" value="<?php echo $this->dbd; ?>">
            <input hidden="hidden" name="tracking" value="<?php echo $this->info_demande_xdistrib['tracking_number_demande_xdistrib']; ?>">
        </div>
        <input class="submit" type="submit" value="enregistrer statut offre">
     </form>
     </div>
         
</div>
